/*******************************************************************************/
/*  This file is auto-generated by GUIX Studio. Do not edit this file by hand. */
/*  Modifications to this file should only be made by running the GUIX Studio  */
/*  application and re-generating the application resource file(s). For more   */
/*  information please refer to the GUIX Studio user's guide, or visit our web */
/*  site at www.expresslogic.com.                                              */
/*                                                                             */
/*  GUIX Studio Revision 5.4.2.9                                               */
/*  Date (dd.mm.yyyy): 21. 2.2022   Time (hh:mm): 09:38                        */
/*******************************************************************************/


#ifndef _MUREVA_LCU_DEMO_LCU_MAINDISPLAY_RESOURCES_H_
#define _MUREVA_LCU_DEMO_LCU_MAINDISPLAY_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define LCU_MAINDISPLAY 0
#define LCU_MAINDISPLAY_COLOR_FORMAT GX_COLOR_FORMAT_24XRGB
#define LCU_MAINDISPLAY_X_RESOLUTION 320
#define LCU_MAINDISPLAY_Y_RESOLUTION 540
#define LCU_MAINDISPLAY_THEME_1 0
#define LCU_MAINDISPLAY_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define LCU_MAINDISPLAY_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_CANVAS 0
#define GX_COLOR_ID_WIDGET_FILL 1
#define GX_COLOR_ID_WINDOW_FILL 2
#define GX_COLOR_ID_DEFAULT_BORDER 3
#define GX_COLOR_ID_WINDOW_BORDER 4
#define GX_COLOR_ID_TEXT 5
#define GX_COLOR_ID_SELECTED_TEXT 6
#define GX_COLOR_ID_SELECTED_FILL 7
#define GX_COLOR_ID_SHADOW 8
#define GX_COLOR_ID_SHINE 9
#define GX_COLOR_ID_BTN_BORDER 10
#define GX_COLOR_ID_BTN_UPPER 11
#define GX_COLOR_ID_BTN_LOWER 12
#define GX_COLOR_ID_BTN_TEXT 13
#define GX_COLOR_ID_SCROLL_FILL 14
#define GX_COLOR_ID_SCROLL_BUTTON 15
#define GX_COLOR_ID_TEXT_INPUT_TEXT 16
#define GX_COLOR_ID_TEXT_INPUT_FILL 17
#define GX_COLOR_ID_SLIDER_TICK 18
#define GX_COLOR_ID_SLIDER_GROOVE_TOP 19
#define GX_COLOR_ID_SLIDER_GROOVE_BOTTOM 20
#define GX_COLOR_ID_SLIDER_NEEDLE_OUTLINE 21
#define GX_COLOR_ID_SLIDER_NEEDLE_FILL 22
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE1 23
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE2 24
#define GX_COLOR_ID_DISABLED_TEXT 25
#define GX_COLOR_ID_DISABLED_FILL 26
#define GX_COLOR_ID_READONLY_TEXT 27
#define GX_COLOR_ID_READONLY_FILL 28
#define GX_COLOR_ID_GREEN_BRIGHT 29
#define GX_COLOR_ID_YELLOW 30
#define GX_COLOR_ID_RADIAL_PROGRESS_BAR_FILL 31
#define GX_COLOR_ID_WHITE 32
#define GX_COLOR_ID_RED_BURNT 33
#define GX_COLOR_ID_GREEN_SUBTLE 34
#define LCU_MAINDISPLAY_COLOR_TABLE_SIZE 35

/* Font ID definitions                                                         */

#define GX_FONT_ID_SYSTEM 0
#define GX_FONT_ID_BUTTON 1
#define GX_FONT_ID_PROMPT 2
#define GX_FONT_ID_TEXT_INPUT 3
#define GX_FONT_ID_VERA_24 4
#define GX_FONT_ID_VERA_BI_24 5
#define GX_FONT_ID_VERA_BI_36 6
#define GX_FONT_ID_VERA_20 7
#define GX_FONT_ID_ARIAL_16 8
#define GX_FONT_ID_ARIAL_20 9
#define LCU_MAINDISPLAY_FONT_TABLE_SIZE 10

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_RADIO_ON 1
#define GX_PIXELMAP_ID_RADIO_OFF 2
#define GX_PIXELMAP_ID_CHECKBOX_ON 3
#define GX_PIXELMAP_ID_CHECKBOX_OFF 4
#define GX_PIXELMAP_ID_BACKDROP 5
#define GX_PIXELMAP_ID_BACKDROPA 6
#define GX_PIXELMAP_ID_DISPLAYRING 7
#define GX_PIXELMAP_ID_DISPLAYRINGA 8
#define GX_PIXELMAP_ID_GREENTICKS 9
#define GX_PIXELMAP_ID_MUREVA_LOGO_133X126 10
#define GX_PIXELMAP_ID_MUREVA_LOGO_180X180 11
#define GX_PIXELMAP_ID_MUREVA_LOGO_REV2 12
#define GX_PIXELMAP_ID_MUREVA_LOGO_ROUNDWHITE 13
#define GX_PIXELMAP_ID_ONESECONDTICKSAMPLE 14
#define GX_PIXELMAP_ID_PAUSEBUTTON_24X16 15
#define GX_PIXELMAP_ID_PAUSEBUTTON_30X20 16
#define GX_PIXELMAP_ID_PAUSEBUTTON_30X30 17
#define GX_PIXELMAP_ID_RIGHTARROW_80X60 18
#define GX_PIXELMAP_ID_STATUSRING_BLUE 19
#define GX_PIXELMAP_ID_STATUSRING_GREEN 20
#define GX_PIXELMAP_ID_STATUSRING_OFF 21
#define GX_PIXELMAP_ID_STATUSRING_RED 22
#define GX_PIXELMAP_ID_STATUSRING_WHITE 23
#define GX_PIXELMAP_ID_WHITE_TEXT_BOX 24
#define LCU_MAINDISPLAY_PIXELMAP_TABLE_SIZE 25

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_25 2
#define GX_STRING_ID_STRING_26 3
#define GX_STRING_ID_STRING_27 4
#define GX_STRING_ID_STRING_28 5
#define GX_STRING_ID_STRING_29 6
#define GX_STRING_ID_STRING_30 7
#define GX_STRING_ID_STRING_2 8
#define GX_STRING_ID_STRING_3 9
#define GX_STRING_ID_STRING_4 10
#define GX_STRING_ID_STRING_5 11
#define GX_STRING_ID_STRING_6 12
#define GX_STRING_ID_STRING_7 13
#define GX_STRING_ID_STRING_10 14
#define GX_STRING_ID_STRING_8 15
#define GX_STRING_ID_STRING_9 16
#define GX_STRING_ID_STRING_11 17
#define GX_STRING_ID_STRING_12 18
#define GX_STRING_ID_STRING_13 19
#define GX_STRING_ID_STRING_14 20
#define GX_STRING_ID_STRING_15 21
#define GX_STRING_ID_STRING_16 22
#define GX_STRING_ID_STRING_17 23
#define GX_STRING_ID_STRING_18 24
#define GX_STRING_ID_STRING_19 25
#define GX_STRING_ID_STRING_20 26
#define GX_STRING_ID_STRING_21 27
#define GX_STRING_ID_STRING_22 28
#define GX_STRING_ID_STRING_23 29
#define GX_STRING_ID_STRING_24 30
#define GX_STRING_ID_STRING_31 31
#define GX_STRING_ID_STRING_32 32
#define GX_STRING_ID_STRING_33 33
#define GX_STRING_ID_STRING_34 34
#define GX_STRING_ID_STRING_39 35
#define GX_STRING_ID_STRING_40 36
#define GX_STRING_ID_STRING_35 37
#define GX_STRING_ID_STRING_36 38
#define GX_STRING_ID_STRING_37 39
#define GX_STRING_ID_STRING_38 40
#define LCU_MAINDISPLAY_STRING_TABLE_SIZE 41

#endif                                       /* sentry                         */
