/*******************************************************************************/
/*  This file is auto-generated by GUIX Studio. Do not edit this file by hand. */
/*  Modifications to this file should only be made by running the GUIX Studio  */
/*  application and re-generating the application. For more information please */
/*  refer to the GUIX Studio user's guide, or visit our web site at            */
/*  www.expresslogic.com.                                                      */
/*                                                                             */
/*  GUIX Studio Revision 5.4.2.9                                               */
/*  Date (dd.mm.yyyy): 28. 2.2022   Time (hh:mm): 12:35                        */
/*******************************************************************************/


#define GUIX_STUDIO_GENERATED_FILE
#include <stddef.h>
#include "MuReva_LCU_Demo_resources.h"
#include "MuReva_LCU_Demo_specifications.h"

static GX_WIDGET *gx_studio_nested_widget_create(GX_BYTE *control, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent);
READYSCREEN_CONTROL_BLOCK ReadyScreen;
SPLASH_WINDOW_CONTROL_BLOCK Splash_Window;
SAMPLE_TICK_WINDOW_CONTROL_BLOCK Sample_Tick_Window;
GX_DISPLAY LCU_MainDisplay_control_block;
GX_WINDOW_ROOT LCU_MainDisplay_root_window;
GX_CANVAS  LCU_MainDisplay_canvas_control_block;
ULONG      LCU_MainDisplay_canvas_memory[172800];


UINT gx_studio_text_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_TEXT_BUTTON *button = (GX_TEXT_BUTTON *) control_block;
    GX_TEXT_BUTTON_PROPERTIES *props = (GX_TEXT_BUTTON_PROPERTIES *) info->properties;
    status = gx_text_button_create(button, info->widget_name, parent, props->string_id, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        gx_text_button_font_set(button, props->font_id);
#if defined(GUIX_5_4_0_COMPATIBILITY)
        gx_text_button_text_color_set(button, props->normal_text_color_id, props->selected_text_color_id);
#else
        gx_text_button_text_color_set(button, props->normal_text_color_id, props->selected_text_color_id, props->disabled_text_color_id);
#endif
    }
    return status;
}

UINT gx_studio_multi_line_text_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_MULTI_LINE_TEXT_BUTTON *button = (GX_MULTI_LINE_TEXT_BUTTON *) control_block;
    GX_ML_TEXT_BUTTON_PROPERTIES *props = (GX_ML_TEXT_BUTTON_PROPERTIES *) info->properties;
    status = gx_multi_line_text_button_create(button, info->widget_name, parent, props->string_id, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        gx_text_button_font_set((GX_TEXT_BUTTON *) button, props->font_id);
#if defined(GUIX_5_4_0_COMPATIBILITY)
        gx_text_button_text_color_set((GX_TEXT_BUTTON *) button, props->normal_text_color_id, props->selected_text_color_id);
#else
        gx_text_button_text_color_set((GX_TEXT_BUTTON *) button, props->normal_text_color_id, props->selected_text_color_id, props->disabled_text_color_id);
#endif
    }
    return status;
}

UINT gx_studio_icon_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_ICON_BUTTON *button = (GX_ICON_BUTTON *) control_block;
    GX_ICON_BUTTON_PROPERTIES *props = (GX_ICON_BUTTON_PROPERTIES *) info->properties;
    status = gx_icon_button_create(button, info->widget_name, parent, props->pixelmap_id, info->style, info->widget_id, &info->size);
    return status;
}

UINT gx_studio_icon_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_ICON *icon = (GX_ICON *) control_block;
    GX_ICON_PROPERTIES *props = (GX_ICON_PROPERTIES *) info->properties;
    status = gx_icon_create(icon, info->widget_name, parent, props->normal_pixelmap_id, info->style, info->widget_id, info->size.gx_rectangle_left, info->size.gx_rectangle_top);
    if (props->selected_pixelmap_id)
    {
        gx_icon_pixelmap_set(icon, props->normal_pixelmap_id, props->selected_pixelmap_id);
    }
    return status;
}

UINT gx_studio_radial_progress_bar_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_RADIAL_PROGRESS_BAR *bar = (GX_RADIAL_PROGRESS_BAR *) control_block;
    GX_RADIAL_PROGRESS_BAR_INFO *bar_info = (GX_RADIAL_PROGRESS_BAR_INFO *) info->properties;
    status = gx_radial_progress_bar_create(bar,
                    info->widget_name,
                    parent,
                    bar_info,
                    info->style,
                    info->widget_id);
    return status;
}

UINT gx_studio_prompt_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_PROMPT *prompt = (GX_PROMPT *) control_block;
    GX_PROMPT_PROPERTIES *props = (GX_PROMPT_PROPERTIES *) info->properties;
    status = gx_prompt_create(prompt, info->widget_name, parent, props->string_id, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        gx_prompt_font_set(prompt, props->font_id);
#if defined(GUIX_5_4_0_COMPATIBILITY)
        gx_prompt_text_color_set(prompt, props->normal_text_color_id, props->selected_text_color_id);
#else
        gx_prompt_text_color_set(prompt, props->normal_text_color_id, props->selected_text_color_id, props->disabled_text_color_id);
#endif
    }
    return status;
}

UINT gx_studio_window_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_WINDOW *window = (GX_WINDOW *) control_block;
    GX_WINDOW_PROPERTIES *props = (GX_WINDOW_PROPERTIES *) info->properties;
    status = gx_window_create(window, info->widget_name, parent, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        if (props->wallpaper_id)
        {
            gx_window_wallpaper_set(window, props->wallpaper_id, info->style & GX_STYLE_TILE_WALLPAPER);
        }
    }
    return status;
}

UINT gx_studio_text_input_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_CONST GX_CHAR *text;
    GX_SINGLE_LINE_TEXT_INPUT *input = (GX_SINGLE_LINE_TEXT_INPUT *) control_block;
    GX_PROMPT *prompt = (GX_PROMPT *) input;
    GX_SINGLE_LINE_TEXT_INPUT_PROPERTIES *props = (GX_SINGLE_LINE_TEXT_INPUT_PROPERTIES *) info->properties;
    status = gx_single_line_text_input_create(input, info->widget_name, parent, props->buffer, props->buffer_size, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        gx_prompt_font_set(prompt, props->font_id);
        gx_single_line_text_input_text_color_set(input, props->normal_text_color_id, props->selected_text_color_id,
                                                 props->disabled_text_color_id, props->readonly_text_color_id);
        gx_single_line_text_input_fill_color_set(input, input->gx_widget_normal_fill_color, input->gx_widget_selected_fill_color,
                                                 input->gx_widget_disabled_fill_color, props->readonly_fill_color_id);
        if (props->buffer && props->buffer_size > 0 && props->string_id)
        {
             gx_system_string_get(props->string_id, &text);

             if (text)
             {
                 gx_single_line_text_input_text_set(input, text);
             }
        }
    }
    return status;
}

UINT gx_studio_multi_line_text_view_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_MULTI_LINE_TEXT_VIEW *view = (GX_MULTI_LINE_TEXT_VIEW *) control_block;
    GX_ML_TEXT_VIEW_PROPERTIES *props = (GX_ML_TEXT_VIEW_PROPERTIES *) info->properties;
    status = gx_multi_line_text_view_create(view, info->widget_name, parent, props->string_id, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        gx_multi_line_text_view_font_set(view, props->font_id);
#if defined(GUIX_5_4_0_COMPATIBILITY)
        gx_multi_line_text_view_text_color_set(view, props->normal_text_color_id, props->selected_text_color_id);
#else
        gx_multi_line_text_view_text_color_set(view, props->normal_text_color_id, props->selected_text_color_id, props->disabled_text_color_id);
#endif
        gx_multi_line_text_view_whitespace_set(view, props->whitespace);
        gx_multi_line_text_view_line_space_set(view, props->line_space);
    }
    return status;
}

UINT gx_studio_template_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status = GX_SUCCESS;
    GX_STUDIO_WIDGET derived;
    GX_TEMPLATE_PROPERTIES *props = (GX_TEMPLATE_PROPERTIES *) info->properties;

                                             /* create base widget and children */ 
    derived =            *props->base_info;
    derived.widget_id =   info->widget_id;
    derived.widget_name = info->widget_name;

    if (info->style & GX_STYLE_ENABLED)
    {
        derived.style |= GX_STYLE_ENABLED;
    }
    else
    {
        derived.style &= ~GX_STYLE_ENABLED;
    }
    if (info->status & GX_STATUS_ACCEPTS_FOCUS)
    {
        derived.status |= GX_STATUS_ACCEPTS_FOCUS;
    }
    else
    {
        derived.status &= ~GX_STATUS_ACCEPTS_FOCUS;
    }

    #if defined(GX_WIDGET_USER_DATA)
    derived.user_data =   info->user_data;
    #endif

    control_block = gx_studio_widget_create((GX_BYTE *) control_block, &derived, parent);
    if (control_block)
    {
        if (info->style & GX_STYLE_DYNAMICALLY_ALLOCATED)
        {
            control_block->gx_widget_status |= GX_STATUS_DYNAMICALLY_ALLOCATED;
        }
        if (derived.size.gx_rectangle_left != info->size.gx_rectangle_left ||
            derived.size.gx_rectangle_top != info->size.gx_rectangle_top)
        {
            gx_widget_shift(control_block,
                info->size.gx_rectangle_left - derived.size.gx_rectangle_left,
                info->size.gx_rectangle_top - derived.size.gx_rectangle_top, GX_FALSE);
        }
    }
    else
    {
        status = GX_FAILURE;
    }
    return status;
}
GX_WINDOW_PROPERTIES PrimaryTemplate_properties =
{
    GX_PIXELMAP_ID_BACKDROP                  /* wallpaper pixelmap id          */
};
GX_ICON_BUTTON_PROPERTIES PrimaryTemplate_Attach_IconButton_properties =
{
    GX_PIXELMAP_ID_RADIO_OFF                 /* pixelmap id                    */
};
GX_ICON_BUTTON_PROPERTIES PrimaryTemplate_Play_Button_properties =
{
    GX_PIXELMAP_ID_RIGHTARROW_80X60          /* pixelmap id                    */
};
GX_ML_TEXT_BUTTON_PROPERTIES PrimaryTemplate_SystemError_Button_properties =
{
    GX_STRING_ID_STRING_24,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_BTN_TEXT,                    /* selected text color            */
    GX_COLOR_ID_DISABLED_TEXT                /* disabled text color            */
};
GX_PROMPT_PROPERTIES PrimaryTemplate_Mouthpiece_PromptBox_properties =
{
    0,                                       /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_DISABLED_TEXT                /* disabled text color            */
};
GX_TEXT_BUTTON_PROPERTIES PrimaryTemplate_LimitSwitch_Button_properties =
{
    GX_STRING_ID_ATTACH,                     /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_BTN_TEXT,                    /* selected text color            */
    GX_COLOR_ID_DISABLED_TEXT                /* disabled text color            */
};
GX_TEXT_BUTTON_PROPERTIES PrimaryTemplate_EEPROM_Expired_Button_properties =
{
    GX_STRING_ID_STRING_31,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_BTN_TEXT,                    /* selected text color            */
    GX_COLOR_ID_DISABLED_TEXT                /* disabled text color            */
};
GX_TEXT_BUTTON_PROPERTIES PrimaryTemplate_EEPROM_OK_Button_properties =
{
    GX_STRING_ID_STRING_11,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_BTN_TEXT,                    /* selected text color            */
    GX_COLOR_ID_DISABLED_TEXT                /* disabled text color            */
};
GX_TEXT_BUTTON_PROPERTIES PrimaryTemplate_EEPROM_Fail_Button_properties =
{
    GX_STRING_ID_STRING_4,                   /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_BTN_TEXT,                    /* selected text color            */
    GX_COLOR_ID_DISABLED_TEXT                /* disabled text color            */
};
GX_PROMPT_PROPERTIES PrimaryTemplate_SerialNumber_Prompt_properties =
{
    GX_STRING_ID_STRING_39,                  /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_DISABLED_TEXT                /* disabled text color            */
};
GX_CHAR PrimaryTemplate_SerialNumber_TextInput_buffer[32];
GX_SINGLE_LINE_TEXT_INPUT_PROPERTIES PrimaryTemplate_SerialNumber_TextInput_properties =
{
    GX_STRING_ID_STRING_40,                  /* string id                      */
    GX_FONT_ID_TEXT_INPUT,                   /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_TEXT,                        /* selected text color            */
    GX_COLOR_ID_TEXT,                        /* disabled text color            */
    GX_COLOR_ID_SHADOW,                      /* readonly fill color            */
    GX_COLOR_ID_READONLY_TEXT,               /* readonly text color            */
    PrimaryTemplate_SerialNumber_TextInput_buffer, /* buffer                   */
    32,                                      /* buffer size                    */
};
GX_PROMPT_PROPERTIES PrimaryTemplate_Mouthpiece_Label_properties =
{
    GX_STRING_ID_STRING_48,                  /* string id                      */
    GX_FONT_ID_ARIAL_16,                     /* font id                        */
    GX_COLOR_ID_BTN_BORDER,                  /* normal text color              */
    GX_COLOR_ID_BTN_BORDER,                  /* selected text color            */
    GX_COLOR_ID_BTN_BORDER                   /* disabled text color            */
};
GX_TEXT_BUTTON_PROPERTIES PrimaryTemplate_EEPROM_12HOUR_Button_properties =
{
    GX_STRING_ID_STRING_49,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_BTN_TEXT,                    /* selected text color            */
    GX_COLOR_ID_DISABLED_TEXT                /* disabled text color            */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_SerialNumber_TextInput_define =
{
    "SerialNumber_TextInput",
    GX_TYPE_SINGLE_LINE_TEXT_INPUT,          /* widget type                    */
    SERIAL_NUMBER_TEXT_INPUT_ID,             /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_SINGLE_LINE_TEXT_INPUT),       /* control block size             */
    GX_COLOR_ID_SHADOW,                      /* normal color id                */
    GX_COLOR_ID_SHADOW,                      /* selected color id              */
    GX_COLOR_ID_SHADOW,                      /* disabled color id              */
    gx_studio_text_input_create,             /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {87, 394, 140, 423},                     /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_SerialNumber_TextInput), /* control block */
    (void *) &PrimaryTemplate_SerialNumber_TextInput_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_EEPROM_12HOUR_Button_define =
{
    "EEPROM_12HOUR_Button",
    GX_TYPE_TEXT_BUTTON,                     /* widget type                    */
    EEPROM_12HOUR_BTN_ID,                    /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TEXT_CENTER,   /* style flags              */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_TEXT_BUTTON),                  /* control block size             */
    GX_COLOR_ID_SCROLL_BUTTON,               /* normal color id                */
    GX_COLOR_ID_SCROLL_FILL,                 /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_text_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {202, 416, 289, 443},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_EEPROM_12HOUR_Button), /* control block */
    (void *) &PrimaryTemplate_EEPROM_12HOUR_Button_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_Mouthpiece_Label_define =
{
    "Mouthpiece_Label",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {45, 320, 144, 343},                     /* widget size                    */
    &PrimaryTemplate_EEPROM_12HOUR_Button_define, /* next widget definition    */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_Mouthpiece_Label), /* control block */
    (void *) &PrimaryTemplate_Mouthpiece_Label_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_SerialNumber_Prompt_define =
{
    "SerialNumber_Prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    SERIAL_NUMBER_PROMPT_ID,                 /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_SHADOW,                      /* normal color id                */
    GX_COLOR_ID_SHADOW,                      /* selected color id              */
    GX_COLOR_ID_SHADOW,                      /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {31, 393, 157, 424},                     /* widget size                    */
    &PrimaryTemplate_Mouthpiece_Label_define, /* next widget definition        */
    &PrimaryTemplate_SerialNumber_TextInput_define, /* child widget definition */
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_SerialNumber_Prompt), /* control block */
    (void *) &PrimaryTemplate_SerialNumber_Prompt_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_EEPROM_Fail_Button_define =
{
    "EEPROM_Fail_Button",
    GX_TYPE_TEXT_BUTTON,                     /* widget type                    */
    EEPROM_FAIL_BTN_ID,                      /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TEXT_CENTER,   /* style flags              */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_TEXT_BUTTON),                  /* control block size             */
    GX_COLOR_ID_SCROLL_BUTTON,               /* normal color id                */
    GX_COLOR_ID_SCROLL_FILL,                 /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_text_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {202, 352, 289, 379},                    /* widget size                    */
    &PrimaryTemplate_SerialNumber_Prompt_define, /* next widget definition     */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_EEPROM_Fail_Button), /* control block */
    (void *) &PrimaryTemplate_EEPROM_Fail_Button_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_EEPROM_OK_Button_define =
{
    "EEPROM_OK_Button",
    GX_TYPE_TEXT_BUTTON,                     /* widget type                    */
    EEPROM_OK_BTN_ID,                        /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TEXT_CENTER,   /* style flags              */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_TEXT_BUTTON),                  /* control block size             */
    GX_COLOR_ID_SCROLL_BUTTON,               /* normal color id                */
    GX_COLOR_ID_SCROLL_FILL,                 /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_text_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {202, 320, 289, 347},                    /* widget size                    */
    &PrimaryTemplate_EEPROM_Fail_Button_define, /* next widget definition      */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_EEPROM_OK_Button), /* control block */
    (void *) &PrimaryTemplate_EEPROM_OK_Button_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_EEPROM_Expired_Button_define =
{
    "EEPROM_Expired_Button",
    GX_TYPE_TEXT_BUTTON,                     /* widget type                    */
    EEPROM_EXPIRED_BTN_ID,                   /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TEXT_CENTER,   /* style flags              */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_TEXT_BUTTON),                  /* control block size             */
    GX_COLOR_ID_SCROLL_BUTTON,               /* normal color id                */
    GX_COLOR_ID_SCROLL_FILL,                 /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_text_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {202, 384, 289, 411},                    /* widget size                    */
    &PrimaryTemplate_EEPROM_OK_Button_define, /* next widget definition        */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_EEPROM_Expired_Button), /* control block */
    (void *) &PrimaryTemplate_EEPROM_Expired_Button_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_LimitSwitch_Button_define =
{
    "LimitSwitch_Button",
    GX_TYPE_TEXT_BUTTON,                     /* widget type                    */
    LIMIT_SWITCH_BTN_ID,                     /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TEXT_CENTER,   /* style flags              */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_TEXT_BUTTON),                  /* control block size             */
    GX_COLOR_ID_SCROLL_BUTTON,               /* normal color id                */
    GX_COLOR_ID_SCROLL_FILL,                 /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_text_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {28, 352, 159, 381},                     /* widget size                    */
    &PrimaryTemplate_EEPROM_Expired_Button_define, /* next widget definition   */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_LimitSwitch_Button), /* control block */
    (void *) &PrimaryTemplate_LimitSwitch_Button_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_Mouthpiece_PromptBox_define =
{
    "Mouthpiece_PromptBox",
    GX_TYPE_PROMPT,                          /* widget type                    */
    MOUTHPIECE_PROMPT_ID,                    /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_SHADOW,                      /* normal color id                */
    GX_COLOR_ID_SHADOW,                      /* selected color id              */
    GX_COLOR_ID_SHADOW,                      /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {17, 314, 306, 449},                     /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    &PrimaryTemplate_LimitSwitch_Button_define, /* child widget definition     */
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_Mouthpiece_PromptBox), /* control block */
    (void *) &PrimaryTemplate_Mouthpiece_PromptBox_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_SystemError_Button_define =
{
    "SystemError_Button",
    GX_TYPE_MULTI_LINE_TEXT_BUTTON,          /* widget type                    */
    SYSTEM_ERROR_BTN_ID,                     /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_MULTI_LINE_TEXT_BUTTON),       /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_multi_line_text_button_create,     /* create function            */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {165, 470, 244, 533},                    /* widget size                    */
    &PrimaryTemplate_Mouthpiece_PromptBox_define, /* next widget definition    */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_SystemError_Button), /* control block */
    (void *) &PrimaryTemplate_SystemError_Button_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_Play_Button_define =
{
    "Play_Button",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    PLAY_BTN_ID,                             /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_TEXT_INPUT_FILL,             /* normal color id                */
    GX_COLOR_ID_TEXT_INPUT_TEXT,             /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {59, 471, 138, 530},                     /* widget size                    */
    &PrimaryTemplate_SystemError_Button_define, /* next widget definition      */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_Play_Button), /* control block */
    (void *) &PrimaryTemplate_Play_Button_properties /* extended properties    */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_Attach_IconButton_define =
{
    "Attach_IconButton",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {500, 248, 610, 279},                    /* widget size                    */
    &PrimaryTemplate_Play_Button_define,     /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_Attach_IconButton), /* control block */
    (void *) &PrimaryTemplate_Attach_IconButton_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_define =
{
    "PrimaryTemplate",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(PRIMARYTEMPLATE_CONTROL_BLOCK),   /* control block size             */
    GX_COLOR_ID_SHADOW,                      /* normal color id                */
    GX_COLOR_ID_SHADOW,                      /* selected color id              */
    GX_COLOR_ID_SHADOW,                      /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {0, 0, 319, 539},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &PrimaryTemplate_Attach_IconButton_define, /* child widget                 */
    0,                                       /* control block                  */
    (void *) &PrimaryTemplate_properties     /* extended properties            */
};
GX_TEMPLATE_PROPERTIES ReadyScreen_properties =
{
    &PrimaryTemplate_define,                 /* base info                      */
    gx_studio_window_create,                 /* base create function           */
    {0, 0, 319, 539}                         /* widget size                    */
};
GX_ICON_PROPERTIES ReadyScreen_StatusRing_Icon_properties =
{
    GX_PIXELMAP_ID_STATUSRING_BLUE,          /* normal pixelmap id             */
    0                                        /* selected pixelmap id           */
};
GX_RADIAL_PROGRESS_BAR_INFO ReadyScreen_TherpayTime_RadialProgressBar_properties =
{
    560,                                     /* xcenter                        */
    159,                                     /* ycenter                        */
    90,                                      /* radius                         */
    359,                                     /* current val                    */
    90,                                      /* anchor val                     */
    GX_FONT_ID_SYSTEM,                       /* font_id                        */
    GX_COLOR_ID_WHITE,                       /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_WHITE,                       /* disabled text color            */
    10,                                      /* normal brush width             */
    18,                                      /* selected brush width           */
    GX_COLOR_ID_CANVAS,                      /* normal brush color             */
    GX_COLOR_ID_GREEN_SUBTLE,                /* selected brush color           */
};
GX_ICON_BUTTON_PROPERTIES ReadyScreen_PauseIcon_Button_properties =
{
    GX_PIXELMAP_ID_PAUSEBUTTON_24X16         /* pixelmap id                    */
};
GX_PROMPT_PROPERTIES ReadyScreen_Time_Prompt_properties =
{
    GX_STRING_ID_STRING_47,                  /* string id                      */
    GX_FONT_ID_ARIALBOLD_52,                 /* font id                        */
    GX_COLOR_ID_WHITE,                       /* normal text color              */
    GX_COLOR_ID_WHITE,                       /* selected text color            */
    GX_COLOR_ID_WHITE                        /* disabled text color            */
};
GX_ML_TEXT_BUTTON_PROPERTIES ReadyScreen_Information_Button_properties =
{
    GX_STRING_ID_STRING_34,                  /* string id                      */
    GX_FONT_ID_ARIAL_20,                     /* font id                        */
    GX_COLOR_ID_WHITE,                       /* normal text color              */
    GX_COLOR_ID_WHITE,                       /* selected text color            */
    GX_COLOR_ID_DISABLED_TEXT                /* disabled text color            */
};
GX_ICON_PROPERTIES ReadyScreen_GreenTick_Icon_properties =
{
    GX_PIXELMAP_ID_GREENTICKS,               /* normal pixelmap id             */
    0                                        /* selected pixelmap id           */
};
GX_ICON_PROPERTIES ReadyScreen_WhiteBox_Icon_properties =
{
    GX_PIXELMAP_ID_WHITE_TEXT_BOX,           /* normal pixelmap id             */
    0                                        /* selected pixelmap id           */
};
GX_PROMPT_PROPERTIES ReadyScreen_TimeTick_Prompt_properties =
{
    GX_STRING_ID_STRING_43,                  /* string id                      */
    GX_FONT_ID_ARIAL_11PT,                   /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_TEXT,                        /* selected text color            */
    GX_COLOR_ID_WHITE                        /* disabled text color            */
};
GX_ML_TEXT_VIEW_PROPERTIES ReadyScreen_Information_TextView_properties =
{
    GX_STRING_ID_DETACH,                     /* string id                      */
    GX_FONT_ID_ARIAL_20,                     /* font id                        */
    GX_COLOR_ID_WHITE,                       /* normal text color              */
    GX_COLOR_ID_WHITE,                       /* selected text color            */
    GX_COLOR_ID_WHITE,                       /* disabled text color            */
    0,                                       /* whitespace                     */
    0                                        /* line_space                     */
};
GX_PROMPT_PROPERTIES ReadyScreen_Minute_Prompt_properties =
{
    GX_STRING_ID_STRING_46,                  /* string id                      */
    GX_FONT_ID_VERABI_12,                    /* font id                        */
    GX_COLOR_ID_WHITE,                       /* normal text color              */
    GX_COLOR_ID_WHITE,                       /* selected text color            */
    GX_COLOR_ID_WHITE                        /* disabled text color            */
};

GX_CONST GX_STUDIO_WIDGET ReadyScreen_Minute_Prompt_define =
{
    "Minute_Prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    MINUTE_PROMPT_ID,                        /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {160, 165, 205, 188},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(READYSCREEN_CONTROL_BLOCK, ReadyScreen_Minute_Prompt), /* control block */
    (void *) &ReadyScreen_Minute_Prompt_properties /* extended properties      */
};

GX_CONST GX_STUDIO_WIDGET ReadyScreen_Information_TextView_define =
{
    "Information_TextView",
    GX_TYPE_MULTI_LINE_TEXT_VIEW,            /* widget type                    */
    INFORMATION_TEXT_VIEW_ID,                /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_MULTI_LINE_TEXT_VIEW),         /* control block size             */
    GX_COLOR_ID_TEXT_INPUT_FILL,             /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_multi_line_text_view_create,     /* create function              */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {85, 108, 234, 207},                     /* widget size                    */
    &ReadyScreen_Minute_Prompt_define,       /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(READYSCREEN_CONTROL_BLOCK, ReadyScreen_Information_TextView), /* control block */
    (void *) &ReadyScreen_Information_TextView_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET ReadyScreen_TimeTick_Prompt_define =
{
    "TimeTick_Prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    TIME_TICK_PROMPT,                        /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_TEXT,                        /* normal color id                */
    GX_COLOR_ID_TEXT,                        /* selected color id              */
    GX_COLOR_ID_TEXT,                        /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {148, 260, 163, 273},                    /* widget size                    */
    &ReadyScreen_Information_TextView_define, /* next widget definition        */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(READYSCREEN_CONTROL_BLOCK, ReadyScreen_TimeTick_Prompt), /* control block */
    (void *) &ReadyScreen_TimeTick_Prompt_properties /* extended properties    */
};

GX_CONST GX_STUDIO_WIDGET ReadyScreen_WhiteBox_Icon_define =
{
    "WhiteBox_Icon",
    GX_TYPE_ICON,                            /* widget type                    */
    WHITE_BOX_ICON,                          /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_TRANSPARENT|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_YELLOW,                      /* normal color id                */
    GX_COLOR_ID_YELLOW,                      /* selected color id              */
    GX_COLOR_ID_YELLOW,                      /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {65, 84, 254, 233},                      /* widget size                    */
    &ReadyScreen_TimeTick_Prompt_define,     /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(READYSCREEN_CONTROL_BLOCK, ReadyScreen_WhiteBox_Icon), /* control block */
    (void *) &ReadyScreen_WhiteBox_Icon_properties /* extended properties      */
};

GX_CONST GX_STUDIO_WIDGET ReadyScreen_GreenTick_Icon_define =
{
    "GreenTick_Icon",
    GX_TYPE_ICON,                            /* widget type                    */
    GREEN_TICK_ICON,                         /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {475, 70, 646, 246},                     /* widget size                    */
    &ReadyScreen_WhiteBox_Icon_define,       /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(READYSCREEN_CONTROL_BLOCK, ReadyScreen_GreenTick_Icon), /* control block */
    (void *) &ReadyScreen_GreenTick_Icon_properties /* extended properties     */
};

GX_CONST GX_STUDIO_WIDGET ReadyScreen_Information_Button_define =
{
    "Information_Button",
    GX_TYPE_MULTI_LINE_TEXT_BUTTON,          /* widget type                    */
    INFORMATION_BUTTON,                      /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_MULTI_LINE_TEXT_BUTTON),       /* control block size             */
    GX_COLOR_ID_BTN_TEXT,                    /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_multi_line_text_button_create,     /* create function            */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {492, 116, 631, 206},                    /* widget size                    */
    &ReadyScreen_GreenTick_Icon_define,      /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(READYSCREEN_CONTROL_BLOCK, ReadyScreen_Information_Button), /* control block */
    (void *) &ReadyScreen_Information_Button_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET ReadyScreen_Time_Prompt_define =
{
    "Time_Prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    TIME_PROMPT_ID,                          /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {140, 142, 169, 189},                    /* widget size                    */
    &ReadyScreen_Information_Button_define,  /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(READYSCREEN_CONTROL_BLOCK, ReadyScreen_Time_Prompt), /* control block */
    (void *) &ReadyScreen_Time_Prompt_properties /* extended properties        */
};

GX_CONST GX_STUDIO_WIDGET ReadyScreen_PauseIcon_Button_define =
{
    "PauseIcon_Button",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {164, 160, 189, 177},                    /* widget size                    */
    &ReadyScreen_Time_Prompt_define,         /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(READYSCREEN_CONTROL_BLOCK, ReadyScreen_PauseIcon_Button), /* control block */
    (void *) &ReadyScreen_PauseIcon_Button_properties /* extended properties   */
};

GX_CONST GX_STUDIO_WIDGET ReadyScreen_TherpayTime_RadialProgressBar_define =
{
    "TherpayTime_RadialProgressBar",
    GX_TYPE_RADIAL_PROGRESS_BAR,             /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_RADIAL_PROGRESS_ALIAS|GX_STYLE_RADIAL_PROGRESS_ROUND,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_RADIAL_PROGRESS_BAR),          /* control block size             */
    GX_COLOR_ID_RADIAL_PROGRESS_BAR_FILL,     /* normal color id               */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_RADIAL_PROGRESS_BAR_FILL,     /* disabled color id             */
    gx_studio_radial_progress_bar_create,     /* create function               */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {61, 60, 259, 258},                      /* widget size                    */
    &ReadyScreen_PauseIcon_Button_define,    /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(READYSCREEN_CONTROL_BLOCK, ReadyScreen_TherpayTime_RadialProgressBar), /* control block */
    (void *) &ReadyScreen_TherpayTime_RadialProgressBar_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET ReadyScreen_StatusRing_Icon_define =
{
    "StatusRing_Icon",
    GX_TYPE_ICON,                            /* widget type                    */
    STATUS_RING_ICON,                        /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {14, 14, 303, 303},                      /* widget size                    */
    &ReadyScreen_TherpayTime_RadialProgressBar_define, /* next widget definition */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(READYSCREEN_CONTROL_BLOCK, ReadyScreen_StatusRing_Icon), /* control block */
    (void *) &ReadyScreen_StatusRing_Icon_properties /* extended properties    */
};

GX_CONST GX_STUDIO_WIDGET ReadyScreen_define =
{
    "ReadyScreen",
    GX_TYPE_TEMPLATE,                        /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(READYSCREEN_CONTROL_BLOCK),       /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_template_create,               /* create function                */
    (VOID (*)(GX_WIDGET *)) ReadyScreen_Draw_Function, /* drawing function override */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) ReadyScreen_Event_Function, /* event function override */
    {0, 0, 319, 539},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &ReadyScreen_StatusRing_Icon_define,     /* child widget                   */
    0,                                       /* control block                  */
    (void *) &ReadyScreen_properties         /* extended properties            */
};
GX_TEMPLATE_PROPERTIES Splash_Window_properties =
{
    &PrimaryTemplate_define,                 /* base info                      */
    gx_studio_window_create,                 /* base create function           */
    {0, 0, 319, 539}                         /* widget size                    */
};
GX_ICON_PROPERTIES Splash_Window_MuReva_Logo_properties =
{
    GX_PIXELMAP_ID_MUREVA_LOGO_133X126,      /* normal pixelmap id             */
    0                                        /* selected pixelmap id           */
};
GX_ICON_PROPERTIES Splash_Window_StatusRing_Icon_properties =
{
    GX_PIXELMAP_ID_STATUSRING_OFF,           /* normal pixelmap id             */
    GX_PIXELMAP_ID_STATUSRING_GREEN          /* selected pixelmap id           */
};
GX_PROMPT_PROPERTIES Splash_Window_Version_Prompt_properties =
{
    GX_STRING_ID_VERSION,                    /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_DISABLED_TEXT                /* disabled text color            */
};
GX_ICON_PROPERTIES Splash_Window_Mureva_Logo_320x240_properties =
{
    GX_PIXELMAP_ID_MUREVA_LOGO_ROUNDWHITE,   /* normal pixelmap id             */
    0                                        /* selected pixelmap id           */
};

GX_CONST GX_STUDIO_WIDGET Splash_Window_Mureva_Logo_320x240_define =
{
    "Mureva_Logo_320x240",
    GX_TYPE_ICON,                            /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {0, 0, 319, 319},                        /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SPLASH_WINDOW_CONTROL_BLOCK, Splash_Window_Mureva_Logo_320x240), /* control block */
    (void *) &Splash_Window_Mureva_Logo_320x240_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET Splash_Window_Version_Prompt_define =
{
    "Version_Prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {20, 280, 111, 303},                     /* widget size                    */
    &Splash_Window_Mureva_Logo_320x240_define, /* next widget definition       */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SPLASH_WINDOW_CONTROL_BLOCK, Splash_Window_Version_Prompt), /* control block */
    (void *) &Splash_Window_Version_Prompt_properties /* extended properties   */
};

GX_CONST GX_STUDIO_WIDGET Splash_Window_StatusRing_Icon_define =
{
    "StatusRing_Icon",
    GX_TYPE_ICON,                            /* widget type                    */
    STATUS_RING_ICON,                        /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {14, 14, 303, 303},                      /* widget size                    */
    &Splash_Window_Version_Prompt_define,    /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SPLASH_WINDOW_CONTROL_BLOCK, Splash_Window_StatusRing_Icon), /* control block */
    (void *) &Splash_Window_StatusRing_Icon_properties /* extended properties  */
};

GX_CONST GX_STUDIO_WIDGET Splash_Window_MuReva_Logo_define =
{
    "MuReva_Logo",
    GX_TYPE_ICON,                            /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_TEXT_INPUT_TEXT,             /* normal color id                */
    GX_COLOR_ID_TEXT_INPUT_TEXT,             /* selected color id              */
    GX_COLOR_ID_TEXT_INPUT_TEXT,             /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {500, 69, 632, 194},                     /* widget size                    */
    &Splash_Window_StatusRing_Icon_define,   /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SPLASH_WINDOW_CONTROL_BLOCK, Splash_Window_MuReva_Logo), /* control block */
    (void *) &Splash_Window_MuReva_Logo_properties /* extended properties      */
};

GX_CONST GX_STUDIO_WIDGET Splash_Window_define =
{
    "Splash_Window",
    GX_TYPE_TEMPLATE,                        /* widget type                    */
    SPLASH_WINDOW,                           /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(SPLASH_WINDOW_CONTROL_BLOCK),     /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_template_create,               /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) SplashScreen_Event_Function, /* event function override */
    {0, 0, 319, 539},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &Splash_Window_MuReva_Logo_define,       /* child widget                   */
    0,                                       /* control block                  */
    (void *) &Splash_Window_properties       /* extended properties            */
};
GX_TEMPLATE_PROPERTIES Sample_Tick_Window_properties =
{
    &PrimaryTemplate_define,                 /* base info                      */
    gx_studio_window_create,                 /* base create function           */
    {0, 0, 319, 539}                         /* widget size                    */
};
GX_ICON_PROPERTIES Sample_Tick_Window_OneOfSixtyTicks_icon_properties =
{
    GX_PIXELMAP_ID_GREENTICKS,               /* normal pixelmap id             */
    0                                        /* selected pixelmap id           */
};
GX_ICON_PROPERTIES Sample_Tick_Window_icon_properties =
{
    GX_PIXELMAP_ID_CLOCK_IMAGE_51_199_40_REV3, /* normal pixelmap id           */
    0                                        /* selected pixelmap id           */
};
GX_PROMPT_PROPERTIES Sample_Tick_Window_Time_Prompt_properties =
{
    GX_STRING_ID_STRING_42,                  /* string id                      */
    GX_FONT_ID_ARIAL_11PT,                   /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_TEXT,                        /* selected text color            */
    GX_COLOR_ID_WHITE                        /* disabled text color            */
};

GX_CONST GX_STUDIO_WIDGET Sample_Tick_Window_Time_Prompt_define =
{
    "Time_Prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    TIME_PROMPT,                             /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_TEXT_CENTER,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_TEXT,                        /* normal color id                */
    GX_COLOR_ID_TEXT,                        /* selected color id              */
    GX_COLOR_ID_TEXT,                        /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {170, 109, 193, 128},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SAMPLE_TICK_WINDOW_CONTROL_BLOCK, Sample_Tick_Window_Time_Prompt), /* control block */
    (void *) &Sample_Tick_Window_Time_Prompt_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET Sample_Tick_Window_icon_define =
{
    "icon",
    GX_TYPE_ICON,                            /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {563, 117, 617, 162},                    /* widget size                    */
    &Sample_Tick_Window_Time_Prompt_define,  /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SAMPLE_TICK_WINDOW_CONTROL_BLOCK, Sample_Tick_Window_icon), /* control block */
    (void *) &Sample_Tick_Window_icon_properties /* extended properties        */
};

GX_CONST GX_STUDIO_WIDGET Sample_Tick_Window_OneOfSixtyTicks_icon_define =
{
    "OneOfSixtyTicks_icon",
    GX_TYPE_ICON,                            /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {575, 69, 746, 245},                     /* widget size                    */
    &Sample_Tick_Window_icon_define,         /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SAMPLE_TICK_WINDOW_CONTROL_BLOCK, Sample_Tick_Window_OneOfSixtyTicks_icon), /* control block */
    (void *) &Sample_Tick_Window_OneOfSixtyTicks_icon_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET Sample_Tick_Window_define =
{
    "Sample_Tick_Window",
    GX_TYPE_TEMPLATE,                        /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(SAMPLE_TICK_WINDOW_CONTROL_BLOCK), /* control block size            */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_template_create,               /* create function                */
    (VOID (*)(GX_WIDGET *)) Sample_Tick_Window_draw_function, /* drawing function override */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) Sample_Tick_Window_event_function, /* event function override */
    {0, 0, 319, 539},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &Sample_Tick_Window_OneOfSixtyTicks_icon_define, /* child widget           */
    0,                                       /* control block                  */
    (void *) &Sample_Tick_Window_properties  /* extended properties            */
};
GX_CONST GX_STUDIO_WIDGET_ENTRY MuReva_LCU_Demo_widget_table[] =
{
    { &ReadyScreen_define, (GX_WIDGET *) &ReadyScreen },
    { &Splash_Window_define, (GX_WIDGET *) &Splash_Window },
    { &Sample_Tick_Window_define, (GX_WIDGET *) &Sample_Tick_Window },
    {GX_NULL, GX_NULL}
};

static GX_WIDGET *gx_studio_nested_widget_create(GX_BYTE *control, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent)
{
    UINT status = GX_SUCCESS;
    GX_WIDGET *widget = GX_NULL;
    GX_VALUE   list_count = 0;
    GX_VALUE   list_total_count = 0;

    if(parent && (parent->gx_widget_type == GX_TYPE_MENU))
    {
        list_total_count = ((GX_MENU *)parent)->gx_menu_list_total_count;
    }

    while(definition && status == GX_SUCCESS)
    {
        if (definition->create_function)
        {
            if (definition->style & GX_STYLE_DYNAMICALLY_ALLOCATED)
            {
                status = gx_widget_allocate(&widget, definition->control_block_size);
                if (status != GX_SUCCESS)
                {
                    return GX_NULL;
                }
            }
            else
            {
                if (control == GX_NULL)
                {
                    return GX_NULL;
                }
                widget = (GX_WIDGET *) (control + definition->control_block_offset);
            }

            status = definition->create_function(definition, widget, parent);

            if(list_count < list_total_count)
            {
                gx_menu_insert((GX_MENU *)parent, widget);
                ((GX_MENU *)parent)->gx_menu_list_total_count--;
                list_count++;
            }

            if (status == GX_SUCCESS)
            {
                if (definition->widget_type != GX_TYPE_TEMPLATE)
                {
#if defined(GUIX_5_4_0_COMPATIBILITY)
                    gx_widget_fill_color_set(widget, definition->normal_fill_color_id, definition->selected_fill_color_id);
#else
                    gx_widget_fill_color_set(widget, definition->normal_fill_color_id, definition->selected_fill_color_id, definition->disabled_fill_color_id);
#endif
                }

                if (!(definition->status & GX_STATUS_ACCEPTS_FOCUS))
                {
                    gx_widget_status_remove(widget, GX_STATUS_ACCEPTS_FOCUS);
                }

                if (definition->draw_function)
                {
                    gx_widget_draw_set(widget, definition->draw_function);
                }
                if (definition->event_function)
                {
                    gx_widget_event_process_set(widget, definition->event_function);
                }

                #if defined(GX_WIDGET_USER_DATA)
                widget->gx_widget_user_data = definition->user_data;
                #endif

                if (definition->child_widget)
                {
                    gx_studio_nested_widget_create(control, definition->child_widget, widget);
                }
            }
            definition = definition->next_widget;
        }
    }
    return widget;
}

GX_WIDGET *gx_studio_widget_create(GX_BYTE *control, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent)
{
    GX_WIDGET *widget;
    widget = gx_studio_nested_widget_create(control, definition, GX_NULL);

    if (parent && widget)
    {
        gx_widget_attach(parent, widget);
    }
    return widget;
}

UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget)
{
    UINT status = GX_FAILURE;
    GX_CONST GX_STUDIO_WIDGET_ENTRY *entry = MuReva_LCU_Demo_widget_table;
    GX_WIDGET *widget = GX_NULL;

    while(entry->widget_information)
    {
        if (!strcmp(name, entry->widget_information->widget_name))
        {
            widget = gx_studio_widget_create((GX_BYTE *) entry->widget, entry->widget_information, parent);
            if (widget)
            {
                status = GX_SUCCESS;
            }
            break;
        }
        entry++;
    }

    if (new_widget)
    {
        *new_widget = widget;
    }
    return status;
}

extern GX_CONST GX_THEME *LCU_MainDisplay_theme_table[];
extern GX_CONST GX_CHAR **LCU_MainDisplay_language_table[];

GX_STUDIO_DISPLAY_INFO MuReva_LCU_Demo_display_table[1] =
{
    {
    "LCU_MainDisplay",
    "LCU_MainDisplay_canvas",
    LCU_MainDisplay_theme_table,
    LCU_MainDisplay_language_table,
    LCU_MAINDISPLAY_THEME_TABLE_SIZE,
    LCU_MAINDISPLAY_LANGUAGE_TABLE_SIZE,
    LCU_MAINDISPLAY_STRING_TABLE_SIZE,
    320,                                     /* x resolution                   */
    540,                                     /* y resolution                   */
    &LCU_MainDisplay_control_block,
    &LCU_MainDisplay_canvas_control_block,
    &LCU_MainDisplay_root_window,
    LCU_MainDisplay_canvas_memory,           /* canvas memory area             */
    691200                                   /* canvas memory size in bytes    */
    }
};

UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *),
    GX_UBYTE language, USHORT theme, GX_WINDOW_ROOT **return_root)
{
    GX_CONST GX_THEME *theme_ptr;
    GX_RECTANGLE size;

    GX_STUDIO_DISPLAY_INFO *display_info = &MuReva_LCU_Demo_display_table[display];


/* create the requested display                                                */

    gx_display_create(display_info->display,
                      display_info->name,
                      driver,
                      (GX_VALUE) display_info->x_resolution,
                      (GX_VALUE) display_info->y_resolution);


/* install the request theme                                                   */

    if(display_info->theme_table)
    {
        theme_ptr = display_info->theme_table[theme];
        if(theme_ptr)
        {
            gx_display_color_table_set(display_info->display, theme_ptr->theme_color_table, theme_ptr->theme_color_table_size);
            
/* install the color palette if required                                       */
            if (display_info->display->gx_display_driver_palette_set &&
                theme_ptr->theme_palette != NULL)
            {
                display_info->display->gx_display_driver_palette_set(display_info->display, theme_ptr->theme_palette, theme_ptr->theme_palette_size);
            }

            gx_display_font_table_set(display_info->display, theme_ptr->theme_font_table, theme_ptr->theme_font_table_size);
            gx_display_pixelmap_table_set(display_info->display, theme_ptr->theme_pixelmap_table, theme_ptr->theme_pixelmap_table_size);
            gx_system_scroll_appearance_set(theme_ptr->theme_vertical_scroll_style, (GX_SCROLLBAR_APPEARANCE *) &theme_ptr->theme_vertical_scrollbar_appearance);
            gx_system_scroll_appearance_set(theme_ptr->theme_horizontal_scroll_style, (GX_SCROLLBAR_APPEARANCE *) &theme_ptr->theme_horizontal_scrollbar_appearance);
            gx_display_language_table_set(display_info->display, (GX_CHAR ***) display_info->language_table, (GX_UBYTE) display_info->language_table_size, display_info->string_table_size);
            gx_display_active_language_set(display_info->display, language);
        }
    }


/* create the canvas for this display                                          */

    gx_canvas_create(display_info->canvas,
                     display_info->canvas_name,
                     display_info->display,
                     GX_CANVAS_MANAGED | GX_CANVAS_VISIBLE,
                     display_info->x_resolution,
                     display_info->y_resolution,
                     display_info->canvas_memory,
                     display_info->canvas_memory_size);

/* Create the root window for this canvas                                      */

    gx_utility_rectangle_define(&size,
                                0, 0,
                                (GX_VALUE) (display_info->x_resolution - 1),
                                (GX_VALUE) (display_info->y_resolution - 1));

    gx_window_root_create(display_info->root_window,
                          display_info->name,
                          display_info->canvas, GX_STYLE_NONE, 0, &size);
    if (return_root)
    {
        *return_root = display_info->root_window;
    }
    return GX_SUCCESS;
}
#undef GUIX_STUDIO_GENERATED_FILE
