/*******************************************************************************/
/*  This file is auto-generated by GUIX Studio. Do not edit this file by hand. */
/*  Modifications to this file should only be made by running the GUIX Studio  */
/*  application and re-generating the application. For more information please */
/*  refer to the GUIX Studio user's guide, or visit our web site at            */
/*  www.expresslogic.com.                                                      */
/*                                                                             */
/*  GUIX Studio Revision 5.4.2.9                                               */
/*  Date (dd.mm.yyyy): 12. 2.2022   Time (hh:mm): 16:05                        */
/*******************************************************************************/


#define GUIX_STUDIO_GENERATED_FILE
#include <stddef.h>
#include "MuReva_LCU_Demo_resources.h"
#include "MuReva_LCU_Demo_specifications.h"

static GX_WIDGET *gx_studio_nested_widget_create(GX_BYTE *control, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent);
READYSCREEN_CONTROL_BLOCK ReadyScreen;
SPLASH_WINDOW_CONTROL_BLOCK Splash_Window;
SAMPLE_TICK_WINDOW_CONTROL_BLOCK Sample_Tick_Window;
GX_DISPLAY LCU_MainDisplay_control_block;
GX_WINDOW_ROOT LCU_MainDisplay_root_window;
GX_CANVAS  LCU_MainDisplay_canvas_control_block;
ULONG      LCU_MainDisplay_canvas_memory[153600];


UINT gx_studio_text_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_TEXT_BUTTON *button = (GX_TEXT_BUTTON *) control_block;
    GX_TEXT_BUTTON_PROPERTIES *props = (GX_TEXT_BUTTON_PROPERTIES *) info->properties;
    status = gx_text_button_create(button, info->widget_name, parent, props->string_id, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        gx_text_button_font_set(button, props->font_id);
#if defined(GUIX_5_4_0_COMPATIBILITY)
        gx_text_button_text_color_set(button, props->normal_text_color_id, props->selected_text_color_id);
#else
        gx_text_button_text_color_set(button, props->normal_text_color_id, props->selected_text_color_id, props->disabled_text_color_id);
#endif
    }
    return status;
}

UINT gx_studio_multi_line_text_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_MULTI_LINE_TEXT_BUTTON *button = (GX_MULTI_LINE_TEXT_BUTTON *) control_block;
    GX_ML_TEXT_BUTTON_PROPERTIES *props = (GX_ML_TEXT_BUTTON_PROPERTIES *) info->properties;
    status = gx_multi_line_text_button_create(button, info->widget_name, parent, props->string_id, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        gx_text_button_font_set((GX_TEXT_BUTTON *) button, props->font_id);
#if defined(GUIX_5_4_0_COMPATIBILITY)
        gx_text_button_text_color_set((GX_TEXT_BUTTON *) button, props->normal_text_color_id, props->selected_text_color_id);
#else
        gx_text_button_text_color_set((GX_TEXT_BUTTON *) button, props->normal_text_color_id, props->selected_text_color_id, props->disabled_text_color_id);
#endif
    }
    return status;
}

UINT gx_studio_icon_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_ICON_BUTTON *button = (GX_ICON_BUTTON *) control_block;
    GX_ICON_BUTTON_PROPERTIES *props = (GX_ICON_BUTTON_PROPERTIES *) info->properties;
    status = gx_icon_button_create(button, info->widget_name, parent, props->pixelmap_id, info->style, info->widget_id, &info->size);
    return status;
}

UINT gx_studio_icon_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_ICON *icon = (GX_ICON *) control_block;
    GX_ICON_PROPERTIES *props = (GX_ICON_PROPERTIES *) info->properties;
    status = gx_icon_create(icon, info->widget_name, parent, props->normal_pixelmap_id, info->style, info->widget_id, info->size.gx_rectangle_left, info->size.gx_rectangle_top);
    if (props->selected_pixelmap_id)
    {
        gx_icon_pixelmap_set(icon, props->normal_pixelmap_id, props->selected_pixelmap_id);
    }
    return status;
}

UINT gx_studio_radial_progress_bar_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_RADIAL_PROGRESS_BAR *bar = (GX_RADIAL_PROGRESS_BAR *) control_block;
    GX_RADIAL_PROGRESS_BAR_INFO *bar_info = (GX_RADIAL_PROGRESS_BAR_INFO *) info->properties;
    status = gx_radial_progress_bar_create(bar,
                    info->widget_name,
                    parent,
                    bar_info,
                    info->style,
                    info->widget_id);
    return status;
}

UINT gx_studio_prompt_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_PROMPT *prompt = (GX_PROMPT *) control_block;
    GX_PROMPT_PROPERTIES *props = (GX_PROMPT_PROPERTIES *) info->properties;
    status = gx_prompt_create(prompt, info->widget_name, parent, props->string_id, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        gx_prompt_font_set(prompt, props->font_id);
#if defined(GUIX_5_4_0_COMPATIBILITY)
        gx_prompt_text_color_set(prompt, props->normal_text_color_id, props->selected_text_color_id);
#else
        gx_prompt_text_color_set(prompt, props->normal_text_color_id, props->selected_text_color_id, props->disabled_text_color_id);
#endif
    }
    return status;
}

UINT gx_studio_window_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status;
    GX_WINDOW *window = (GX_WINDOW *) control_block;
    GX_WINDOW_PROPERTIES *props = (GX_WINDOW_PROPERTIES *) info->properties;
    status = gx_window_create(window, info->widget_name, parent, info->style, info->widget_id, &info->size);
    if (status == GX_SUCCESS)
    {
        if (props->wallpaper_id)
        {
            gx_window_wallpaper_set(window, props->wallpaper_id, info->style & GX_STYLE_TILE_WALLPAPER);
        }
    }
    return status;
}

UINT gx_studio_template_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent)
{
    UINT status = GX_SUCCESS;
    GX_STUDIO_WIDGET derived;
    GX_TEMPLATE_PROPERTIES *props = (GX_TEMPLATE_PROPERTIES *) info->properties;

                                             /* create base widget and children */ 
    derived =            *props->base_info;
    derived.widget_id =   info->widget_id;
    derived.widget_name = info->widget_name;

    if (info->style & GX_STYLE_ENABLED)
    {
        derived.style |= GX_STYLE_ENABLED;
    }
    else
    {
        derived.style &= ~GX_STYLE_ENABLED;
    }
    if (info->status & GX_STATUS_ACCEPTS_FOCUS)
    {
        derived.status |= GX_STATUS_ACCEPTS_FOCUS;
    }
    else
    {
        derived.status &= ~GX_STATUS_ACCEPTS_FOCUS;
    }

    #if defined(GX_WIDGET_USER_DATA)
    derived.user_data =   info->user_data;
    #endif

    control_block = gx_studio_widget_create((GX_BYTE *) control_block, &derived, parent);
    if (control_block)
    {
        if (info->style & GX_STYLE_DYNAMICALLY_ALLOCATED)
        {
            control_block->gx_widget_status |= GX_STATUS_DYNAMICALLY_ALLOCATED;
        }
        if (derived.size.gx_rectangle_left != info->size.gx_rectangle_left ||
            derived.size.gx_rectangle_top != info->size.gx_rectangle_top)
        {
            gx_widget_shift(control_block,
                info->size.gx_rectangle_left - derived.size.gx_rectangle_left,
                info->size.gx_rectangle_top - derived.size.gx_rectangle_top, GX_FALSE);
        }
    }
    else
    {
        status = GX_FAILURE;
    }
    return status;
}
GX_WINDOW_PROPERTIES PrimaryTemplate_properties =
{
    GX_PIXELMAP_ID_BACKDROPA                 /* wallpaper pixelmap id          */
};
GX_TEXT_BUTTON_PROPERTIES PrimaryTemplate_LimitSwitch_Button_properties =
{
    GX_STRING_ID_STRING_19,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_BTN_TEXT,                    /* selected text color            */
    GX_COLOR_ID_DISABLED_TEXT                /* disabled text color            */
};
GX_ICON_BUTTON_PROPERTIES PrimaryTemplate_LimitSwitchStatus_IconButton_properties =
{
    GX_PIXELMAP_ID_RADIO_OFF                 /* pixelmap id                    */
};
GX_PROMPT_PROPERTIES PrimaryTemplate_EEPROM_Is_Prompt_properties =
{
    GX_STRING_ID_STRING_6,                   /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_TEXT,                        /* selected text color            */
    GX_COLOR_ID_TEXT                         /* disabled text color            */
};
GX_TEXT_BUTTON_PROPERTIES PrimaryTemplate_EEPROM_Fail_Button_properties =
{
    GX_STRING_ID_STRING_4,                   /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_BTN_TEXT,                    /* selected text color            */
    GX_COLOR_ID_DISABLED_TEXT                /* disabled text color            */
};
GX_TEXT_BUTTON_PROPERTIES PrimaryTemplate_EEPROM_Pass_Button_properties =
{
    GX_STRING_ID_STRING_3,                   /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_BTN_TEXT,                    /* selected text color            */
    GX_COLOR_ID_DISABLED_TEXT                /* disabled text color            */
};
GX_TEXT_BUTTON_PROPERTIES PrimaryTemplate_EEPROM_Expired_Button_properties =
{
    GX_STRING_ID_STRING_31,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_BTN_TEXT,                    /* normal text color              */
    GX_COLOR_ID_BTN_TEXT,                    /* selected text color            */
    GX_COLOR_ID_DISABLED_TEXT                /* disabled text color            */
};
GX_ICON_BUTTON_PROPERTIES PrimaryTemplate_Play_Button_properties =
{
    GX_PIXELMAP_ID_RIGHTARROW_80X60          /* pixelmap id                    */
};
GX_PROMPT_PROPERTIES PrimaryTemplate_LimitSwitchStatus_prompt_properties =
{
    GX_STRING_ID_STRING_20,                  /* string id                      */
    GX_FONT_ID_SYSTEM,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_DISABLED_TEXT                /* disabled text color            */
};
GX_TEXT_BUTTON_PROPERTIES PrimaryTemplate_SystemError_Button_properties =
{
    GX_STRING_ID_STRING_24,                  /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_WHITE,                       /* normal text color              */
    GX_COLOR_ID_SCROLL_BUTTON,               /* selected text color            */
    GX_COLOR_ID_DISABLED_TEXT                /* disabled text color            */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_EEPROM_Expired_Button_define =
{
    "EEPROM_Expired_Button",
    GX_TYPE_TEXT_BUTTON,                     /* widget type                    */
    EEPROM_EXPIRED_BTN_ID,                   /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TEXT_CENTER,   /* style flags              */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_TEXT_BUTTON),                  /* control block size             */
    GX_COLOR_ID_SCROLL_BUTTON,               /* normal color id                */
    GX_COLOR_ID_SCROLL_FILL,                 /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_text_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {182, 327, 295, 354},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_EEPROM_Expired_Button), /* control block */
    (void *) &PrimaryTemplate_EEPROM_Expired_Button_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_EEPROM_Pass_Button_define =
{
    "EEPROM_Pass_Button",
    GX_TYPE_TEXT_BUTTON,                     /* widget type                    */
    EEPROM_PASS_BTN_ID,                      /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TEXT_CENTER,   /* style flags              */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_TEXT_BUTTON),                  /* control block size             */
    GX_COLOR_ID_SCROLL_BUTTON,               /* normal color id                */
    GX_COLOR_ID_SCROLL_FILL,                 /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_text_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {182, 292, 231, 319},                    /* widget size                    */
    &PrimaryTemplate_EEPROM_Expired_Button_define, /* next widget definition   */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_EEPROM_Pass_Button), /* control block */
    (void *) &PrimaryTemplate_EEPROM_Pass_Button_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_EEPROM_Fail_Button_define =
{
    "EEPROM_Fail_Button",
    GX_TYPE_TEXT_BUTTON,                     /* widget type                    */
    EEPROM_FAIL_BTN_ID,                      /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TEXT_CENTER,   /* style flags              */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_TEXT_BUTTON),                  /* control block size             */
    GX_COLOR_ID_SCROLL_BUTTON,               /* normal color id                */
    GX_COLOR_ID_SCROLL_FILL,                 /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_text_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {244, 292, 293, 319},                    /* widget size                    */
    &PrimaryTemplate_EEPROM_Pass_Button_define, /* next widget definition      */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_EEPROM_Fail_Button), /* control block */
    (void *) &PrimaryTemplate_EEPROM_Fail_Button_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_SystemError_Button_define =
{
    "SystemError_Button",
    GX_TYPE_TEXT_BUTTON,                     /* widget type                    */
    SYSTEM_ERROR_BTN_ID,                     /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_TEXT_BUTTON),                  /* control block size             */
    GX_COLOR_ID_RED_BURNT,                   /* normal color id                */
    GX_COLOR_ID_RED_BURNT,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_text_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {41, 369, 290, 398},                     /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_SystemError_Button), /* control block */
    (void *) &PrimaryTemplate_SystemError_Button_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_LimitSwitchStatus_prompt_define =
{
    "LimitSwitchStatus_prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {176, 250, 255, 273},                    /* widget size                    */
    &PrimaryTemplate_SystemError_Button_define, /* next widget definition      */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_LimitSwitchStatus_prompt), /* control block */
    (void *) &PrimaryTemplate_LimitSwitchStatus_prompt_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_Play_Button_define =
{
    "Play_Button",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    PLAY_BTN_ID,                             /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {113, 408, 192, 467},                    /* widget size                    */
    &PrimaryTemplate_LimitSwitchStatus_prompt_define, /* next widget definition */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_Play_Button), /* control block */
    (void *) &PrimaryTemplate_Play_Button_properties /* extended properties    */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_EEPROM_Is_Prompt_define =
{
    "EEPROM_Is_Prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_LEFT,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_WIDGET_FILL,                 /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {20, 285, 308, 361},                     /* widget size                    */
    &PrimaryTemplate_Play_Button_define,     /* next widget definition         */
    &PrimaryTemplate_EEPROM_Fail_Button_define, /* child widget definition     */
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_EEPROM_Is_Prompt), /* control block */
    (void *) &PrimaryTemplate_EEPROM_Is_Prompt_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_LimitSwitchStatus_IconButton_define =
{
    "LimitSwitchStatus_IconButton",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {500, 248, 610, 279},                    /* widget size                    */
    &PrimaryTemplate_EEPROM_Is_Prompt_define, /* next widget definition        */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_LimitSwitchStatus_IconButton), /* control block */
    (void *) &PrimaryTemplate_LimitSwitchStatus_IconButton_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_LimitSwitch_Button_define =
{
    "LimitSwitch_Button",
    GX_TYPE_TEXT_BUTTON,                     /* widget type                    */
    LIMIT_SWITCH_BTN_ID,                     /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_TEXT_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_text_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {20, 247, 151, 276},                     /* widget size                    */
    &PrimaryTemplate_LimitSwitchStatus_IconButton_define, /* next widget definition */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(PRIMARYTEMPLATE_CONTROL_BLOCK, PrimaryTemplate_LimitSwitch_Button), /* control block */
    (void *) &PrimaryTemplate_LimitSwitch_Button_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET PrimaryTemplate_define =
{
    "PrimaryTemplate",
    GX_TYPE_WINDOW,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(PRIMARYTEMPLATE_CONTROL_BLOCK),   /* control block size             */
    GX_COLOR_ID_SHADOW,                      /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {0, 0, 319, 479},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &PrimaryTemplate_LimitSwitch_Button_define, /* child widget                */
    0,                                       /* control block                  */
    (void *) &PrimaryTemplate_properties     /* extended properties            */
};
GX_TEMPLATE_PROPERTIES ReadyScreen_properties =
{
    &PrimaryTemplate_define,                 /* base info                      */
    gx_studio_window_create,                 /* base create function           */
    {0, 0, 319, 479}                         /* widget size                    */
};
GX_ICON_PROPERTIES ReadyScreen_StatusRing_Icon_properties =
{
    GX_PIXELMAP_ID_STATUSRING_WHITE,         /* normal pixelmap id             */
    0                                        /* selected pixelmap id           */
};
GX_RADIAL_PROGRESS_BAR_INFO ReadyScreen_TherpayTime_RadialProgressBar_properties =
{
    160,                                     /* xcenter                        */
    109,                                     /* ycenter                        */
    76,                                      /* radius                         */
    -180,                                    /* current val                    */
    90,                                      /* anchor val                     */
    GX_FONT_ID_SYSTEM,                       /* font_id                        */
    GX_COLOR_ID_WHITE,                       /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_WHITE,                       /* disabled text color            */
    8,                                       /* normal brush width             */
    10,                                      /* selected brush width           */
    GX_COLOR_ID_CANVAS,                      /* normal brush color             */
    GX_COLOR_ID_GREEN_BRIGHT,                /* selected brush color           */
};
GX_ICON_BUTTON_PROPERTIES ReadyScreen_PauseIcon_Button_properties =
{
    GX_PIXELMAP_ID_PAUSEBUTTON_24X16         /* pixelmap id                    */
};
GX_PROMPT_PROPERTIES ReadyScreen_Time_Prompt_properties =
{
    GX_STRING_ID_STRING_22,                  /* string id                      */
    GX_FONT_ID_VERA_BI_36,                   /* font id                        */
    GX_COLOR_ID_WHITE,                       /* normal text color              */
    GX_COLOR_ID_WHITE,                       /* selected text color            */
    GX_COLOR_ID_WHITE                        /* disabled text color            */
};
GX_ML_TEXT_BUTTON_PROPERTIES ReadyScreen_Information_Button_properties =
{
    GX_STRING_ID_STRING_9,                   /* string id                      */
    GX_FONT_ID_ARIAL_20,                     /* font id                        */
    GX_COLOR_ID_WHITE,                       /* normal text color              */
    GX_COLOR_ID_WHITE,                       /* selected text color            */
    GX_COLOR_ID_DISABLED_TEXT                /* disabled text color            */
};
GX_ICON_PROPERTIES ReadyScreen_GreenTick_Icon_properties =
{
    GX_PIXELMAP_ID_GREENTICKS,               /* normal pixelmap id             */
    0                                        /* selected pixelmap id           */
};

GX_CONST GX_STUDIO_WIDGET ReadyScreen_GreenTick_Icon_define =
{
    "GreenTick_Icon",
    GX_TYPE_ICON,                            /* widget type                    */
    GREEN_TICK_ICON,                         /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {476, 21, 647, 197},                     /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(READYSCREEN_CONTROL_BLOCK, ReadyScreen_GreenTick_Icon), /* control block */
    (void *) &ReadyScreen_GreenTick_Icon_properties /* extended properties     */
};

GX_CONST GX_STUDIO_WIDGET ReadyScreen_Information_Button_define =
{
    "Information_Button",
    GX_TYPE_MULTI_LINE_TEXT_BUTTON,          /* widget type                    */
    INFORMATION_BUTTON,                      /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_MULTI_LINE_TEXT_BUTTON),       /* control block size             */
    GX_COLOR_ID_BTN_TEXT,                    /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_multi_line_text_button_create,     /* create function            */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {92, 63, 231, 153},                      /* widget size                    */
    &ReadyScreen_GreenTick_Icon_define,      /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(READYSCREEN_CONTROL_BLOCK, ReadyScreen_Information_Button), /* control block */
    (void *) &ReadyScreen_Information_Button_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET ReadyScreen_Time_Prompt_define =
{
    "Time_Prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    TIME_PROMPT_ID,                          /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {106, 104, 215, 143},                    /* widget size                    */
    &ReadyScreen_Information_Button_define,  /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(READYSCREEN_CONTROL_BLOCK, ReadyScreen_Time_Prompt), /* control block */
    (void *) &ReadyScreen_Time_Prompt_properties /* extended properties        */
};

GX_CONST GX_STUDIO_WIDGET ReadyScreen_PauseIcon_Button_define =
{
    "PauseIcon_Button",
    GX_TYPE_ICON_BUTTON,                     /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_CENTER|GX_STYLE_VALIGN_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON_BUTTON),                  /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {169, 108, 194, 125},                    /* widget size                    */
    &ReadyScreen_Time_Prompt_define,         /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(READYSCREEN_CONTROL_BLOCK, ReadyScreen_PauseIcon_Button), /* control block */
    (void *) &ReadyScreen_PauseIcon_Button_properties /* extended properties   */
};

GX_CONST GX_STUDIO_WIDGET ReadyScreen_TherpayTime_RadialProgressBar_define =
{
    "TherpayTime_RadialProgressBar",
    GX_TYPE_RADIAL_PROGRESS_BAR,             /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_RADIAL_PROGRESS_ALIAS|GX_STYLE_RADIAL_PROGRESS_ROUND,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_RADIAL_PROGRESS_BAR),          /* control block size             */
    GX_COLOR_ID_RADIAL_PROGRESS_BAR_FILL,     /* normal color id               */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_RADIAL_PROGRESS_BAR_FILL,     /* disabled color id             */
    gx_studio_radial_progress_bar_create,     /* create function               */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {477, 24, 645, 192},                     /* widget size                    */
    &ReadyScreen_PauseIcon_Button_define,    /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(READYSCREEN_CONTROL_BLOCK, ReadyScreen_TherpayTime_RadialProgressBar), /* control block */
    (void *) &ReadyScreen_TherpayTime_RadialProgressBar_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET ReadyScreen_StatusRing_Icon_define =
{
    "StatusRing_Icon",
    GX_TYPE_ICON,                            /* widget type                    */
    STATUS_RING_ICON,                        /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {52, 0, 271, 219},                       /* widget size                    */
    &ReadyScreen_TherpayTime_RadialProgressBar_define, /* next widget definition */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(READYSCREEN_CONTROL_BLOCK, ReadyScreen_StatusRing_Icon), /* control block */
    (void *) &ReadyScreen_StatusRing_Icon_properties /* extended properties    */
};

GX_CONST GX_STUDIO_WIDGET ReadyScreen_define =
{
    "ReadyScreen",
    GX_TYPE_TEMPLATE,                        /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(READYSCREEN_CONTROL_BLOCK),       /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_template_create,               /* create function                */
    (VOID (*)(GX_WIDGET *)) ReadyScreen_Draw_Function, /* drawing function override */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) ReadyScreen_Event_Function, /* event function override */
    {0, 0, 319, 479},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &ReadyScreen_StatusRing_Icon_define,     /* child widget                   */
    0,                                       /* control block                  */
    (void *) &ReadyScreen_properties         /* extended properties            */
};
GX_TEMPLATE_PROPERTIES Splash_Window_properties =
{
    &PrimaryTemplate_define,                 /* base info                      */
    gx_studio_window_create,                 /* base create function           */
    {0, 0, 319, 479}                         /* widget size                    */
};
GX_ICON_PROPERTIES Splash_Window_MuReva_Logo_properties =
{
    GX_PIXELMAP_ID_MUREVA_LOGO_133X126,      /* normal pixelmap id             */
    0                                        /* selected pixelmap id           */
};
GX_ICON_PROPERTIES Splash_Window_StatusRing_Icon_properties =
{
    GX_PIXELMAP_ID_STATUSRING_WHITE,         /* normal pixelmap id             */
    0                                        /* selected pixelmap id           */
};
GX_PROMPT_PROPERTIES Splash_Window_prompt_properties =
{
    GX_STRING_ID_STRING_21,                  /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_DISABLED_TEXT                /* disabled text color            */
};

GX_CONST GX_STUDIO_WIDGET Splash_Window_prompt_define =
{
    "prompt",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {114, 158, 204, 181},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SPLASH_WINDOW_CONTROL_BLOCK, Splash_Window_prompt), /* control block */
    (void *) &Splash_Window_prompt_properties /* extended properties           */
};

GX_CONST GX_STUDIO_WIDGET Splash_Window_StatusRing_Icon_define =
{
    "StatusRing_Icon",
    GX_TYPE_ICON,                            /* widget type                    */
    STATUS_RING_ICON,                        /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {52, 0, 271, 219},                       /* widget size                    */
    &Splash_Window_prompt_define,            /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SPLASH_WINDOW_CONTROL_BLOCK, Splash_Window_StatusRing_Icon), /* control block */
    (void *) &Splash_Window_StatusRing_Icon_properties /* extended properties  */
};

GX_CONST GX_STUDIO_WIDGET Splash_Window_MuReva_Logo_define =
{
    "MuReva_Logo",
    GX_TYPE_ICON,                            /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_TEXT_INPUT_TEXT,             /* normal color id                */
    GX_COLOR_ID_TEXT_INPUT_TEXT,             /* selected color id              */
    GX_COLOR_ID_TEXT_INPUT_TEXT,             /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {96, 36, 228, 161},                      /* widget size                    */
    &Splash_Window_StatusRing_Icon_define,   /* next widget definition         */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SPLASH_WINDOW_CONTROL_BLOCK, Splash_Window_MuReva_Logo), /* control block */
    (void *) &Splash_Window_MuReva_Logo_properties /* extended properties      */
};

GX_CONST GX_STUDIO_WIDGET Splash_Window_define =
{
    "Splash_Window",
    GX_TYPE_TEMPLATE,                        /* widget type                    */
    SPLAS_WINDOW,                            /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(SPLASH_WINDOW_CONTROL_BLOCK),     /* control block size             */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_template_create,               /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) SplashScreen_Event_Function, /* event function override */
    {0, 0, 319, 479},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &Splash_Window_MuReva_Logo_define,       /* child widget                   */
    0,                                       /* control block                  */
    (void *) &Splash_Window_properties       /* extended properties            */
};
GX_TEMPLATE_PROPERTIES Sample_Tick_Window_properties =
{
    &PrimaryTemplate_define,                 /* base info                      */
    gx_studio_window_create,                 /* base create function           */
    {0, 0, 319, 479}                         /* widget size                    */
};
GX_ICON_PROPERTIES Sample_Tick_Window_OneOfSixtyTicks_icon_properties =
{
    GX_PIXELMAP_ID_ONESECONDTICKSAMPLE,      /* normal pixelmap id             */
    0                                        /* selected pixelmap id           */
};

GX_CONST GX_STUDIO_WIDGET Sample_Tick_Window_OneOfSixtyTicks_icon_define =
{
    "OneOfSixtyTicks_icon",
    GX_TYPE_ICON,                            /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {38, 22, 277, 201},                      /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    offsetof(SAMPLE_TICK_WINDOW_CONTROL_BLOCK, Sample_Tick_Window_OneOfSixtyTicks_icon), /* control block */
    (void *) &Sample_Tick_Window_OneOfSixtyTicks_icon_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET Sample_Tick_Window_define =
{
    "Sample_Tick_Window",
    GX_TYPE_TEMPLATE,                        /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_ENABLED,   /* style flags                    */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(SAMPLE_TICK_WINDOW_CONTROL_BLOCK), /* control block size            */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_DISABLED_FILL,               /* disabled color id              */
    gx_studio_template_create,               /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {0, 0, 319, 479},                        /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &Sample_Tick_Window_OneOfSixtyTicks_icon_define, /* child widget           */
    0,                                       /* control block                  */
    (void *) &Sample_Tick_Window_properties  /* extended properties            */
};
GX_CONST GX_STUDIO_WIDGET_ENTRY MuReva_LCU_Demo_widget_table[] =
{
    { &ReadyScreen_define, (GX_WIDGET *) &ReadyScreen },
    { &Splash_Window_define, (GX_WIDGET *) &Splash_Window },
    { &Sample_Tick_Window_define, (GX_WIDGET *) &Sample_Tick_Window },
    {GX_NULL, GX_NULL}
};

static GX_WIDGET *gx_studio_nested_widget_create(GX_BYTE *control, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent)
{
    UINT status = GX_SUCCESS;
    GX_WIDGET *widget = GX_NULL;
    GX_VALUE   list_count = 0;
    GX_VALUE   list_total_count = 0;

    if(parent && (parent->gx_widget_type == GX_TYPE_MENU))
    {
        list_total_count = ((GX_MENU *)parent)->gx_menu_list_total_count;
    }

    while(definition && status == GX_SUCCESS)
    {
        if (definition->create_function)
        {
            if (definition->style & GX_STYLE_DYNAMICALLY_ALLOCATED)
            {
                status = gx_widget_allocate(&widget, definition->control_block_size);
                if (status != GX_SUCCESS)
                {
                    return GX_NULL;
                }
            }
            else
            {
                if (control == GX_NULL)
                {
                    return GX_NULL;
                }
                widget = (GX_WIDGET *) (control + definition->control_block_offset);
            }

            status = definition->create_function(definition, widget, parent);

            if(list_count < list_total_count)
            {
                gx_menu_insert((GX_MENU *)parent, widget);
                ((GX_MENU *)parent)->gx_menu_list_total_count--;
                list_count++;
            }

            if (status == GX_SUCCESS)
            {
                if (definition->widget_type != GX_TYPE_TEMPLATE)
                {
#if defined(GUIX_5_4_0_COMPATIBILITY)
                    gx_widget_fill_color_set(widget, definition->normal_fill_color_id, definition->selected_fill_color_id);
#else
                    gx_widget_fill_color_set(widget, definition->normal_fill_color_id, definition->selected_fill_color_id, definition->disabled_fill_color_id);
#endif
                }

                if (!(definition->status & GX_STATUS_ACCEPTS_FOCUS))
                {
                    gx_widget_status_remove(widget, GX_STATUS_ACCEPTS_FOCUS);
                }

                if (definition->draw_function)
                {
                    gx_widget_draw_set(widget, definition->draw_function);
                }
                if (definition->event_function)
                {
                    gx_widget_event_process_set(widget, definition->event_function);
                }

                #if defined(GX_WIDGET_USER_DATA)
                widget->gx_widget_user_data = definition->user_data;
                #endif

                if (definition->child_widget)
                {
                    gx_studio_nested_widget_create(control, definition->child_widget, widget);
                }
            }
            definition = definition->next_widget;
        }
    }
    return widget;
}

GX_WIDGET *gx_studio_widget_create(GX_BYTE *control, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent)
{
    GX_WIDGET *widget;
    widget = gx_studio_nested_widget_create(control, definition, GX_NULL);

    if (parent && widget)
    {
        gx_widget_attach(parent, widget);
    }
    return widget;
}

UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget)
{
    UINT status = GX_FAILURE;
    GX_CONST GX_STUDIO_WIDGET_ENTRY *entry = MuReva_LCU_Demo_widget_table;
    GX_WIDGET *widget = GX_NULL;

    while(entry->widget_information)
    {
        if (!strcmp(name, entry->widget_information->widget_name))
        {
            widget = gx_studio_widget_create((GX_BYTE *) entry->widget, entry->widget_information, parent);
            if (widget)
            {
                status = GX_SUCCESS;
            }
            break;
        }
        entry++;
    }

    if (new_widget)
    {
        *new_widget = widget;
    }
    return status;
}

extern GX_CONST GX_THEME *LCU_MainDisplay_theme_table[];
extern GX_CONST GX_CHAR **LCU_MainDisplay_language_table[];

GX_STUDIO_DISPLAY_INFO MuReva_LCU_Demo_display_table[1] =
{
    {
    "LCU_MainDisplay",
    "LCU_MainDisplay_canvas",
    LCU_MainDisplay_theme_table,
    LCU_MainDisplay_language_table,
    LCU_MAINDISPLAY_THEME_TABLE_SIZE,
    LCU_MAINDISPLAY_LANGUAGE_TABLE_SIZE,
    LCU_MAINDISPLAY_STRING_TABLE_SIZE,
    320,                                     /* x resolution                   */
    480,                                     /* y resolution                   */
    &LCU_MainDisplay_control_block,
    &LCU_MainDisplay_canvas_control_block,
    &LCU_MainDisplay_root_window,
    LCU_MainDisplay_canvas_memory,           /* canvas memory area             */
    614400                                   /* canvas memory size in bytes    */
    }
};

UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *),
    GX_UBYTE language, USHORT theme, GX_WINDOW_ROOT **return_root)
{
    GX_CONST GX_THEME *theme_ptr;
    GX_RECTANGLE size;

    GX_STUDIO_DISPLAY_INFO *display_info = &MuReva_LCU_Demo_display_table[display];


/* create the requested display                                                */

    gx_display_create(display_info->display,
                      display_info->name,
                      driver,
                      (GX_VALUE) display_info->x_resolution,
                      (GX_VALUE) display_info->y_resolution);


/* install the request theme                                                   */

    if(display_info->theme_table)
    {
        theme_ptr = display_info->theme_table[theme];
        if(theme_ptr)
        {
            gx_display_color_table_set(display_info->display, theme_ptr->theme_color_table, theme_ptr->theme_color_table_size);
            
/* install the color palette if required                                       */
            if (display_info->display->gx_display_driver_palette_set &&
                theme_ptr->theme_palette != NULL)
            {
                display_info->display->gx_display_driver_palette_set(display_info->display, theme_ptr->theme_palette, theme_ptr->theme_palette_size);
            }

            gx_display_font_table_set(display_info->display, theme_ptr->theme_font_table, theme_ptr->theme_font_table_size);
            gx_display_pixelmap_table_set(display_info->display, theme_ptr->theme_pixelmap_table, theme_ptr->theme_pixelmap_table_size);
            gx_system_scroll_appearance_set(theme_ptr->theme_vertical_scroll_style, (GX_SCROLLBAR_APPEARANCE *) &theme_ptr->theme_vertical_scrollbar_appearance);
            gx_system_scroll_appearance_set(theme_ptr->theme_horizontal_scroll_style, (GX_SCROLLBAR_APPEARANCE *) &theme_ptr->theme_horizontal_scrollbar_appearance);
            gx_display_language_table_set(display_info->display, (GX_CHAR ***) display_info->language_table, (GX_UBYTE) display_info->language_table_size, display_info->string_table_size);
            gx_display_active_language_set(display_info->display, language);
        }
    }


/* create the canvas for this display                                          */

    gx_canvas_create(display_info->canvas,
                     display_info->canvas_name,
                     display_info->display,
                     GX_CANVAS_MANAGED | GX_CANVAS_VISIBLE,
                     display_info->x_resolution,
                     display_info->y_resolution,
                     display_info->canvas_memory,
                     display_info->canvas_memory_size);

/* Create the root window for this canvas                                      */

    gx_utility_rectangle_define(&size,
                                0, 0,
                                (GX_VALUE) (display_info->x_resolution - 1),
                                (GX_VALUE) (display_info->y_resolution - 1));

    gx_window_root_create(display_info->root_window,
                          display_info->name,
                          display_info->canvas, GX_STYLE_NONE, 0, &size);
    if (return_root)
    {
        *return_root = display_info->root_window;
    }
    return GX_SUCCESS;
}
#undef GUIX_STUDIO_GENERATED_FILE
