/*******************************************************************************/
/*  This file is auto-generated by GUIX Studio. Do not edit this file by hand. */
/*  Modifications to this file should only be made by running the GUIX Studio  */
/*  application and re-generating the application resource file(s). For more   */
/*  information please refer to the GUIX Studio user's guide, or visit our web */
/*  site at www.expresslogic.com.                                              */
/*                                                                             */
/*  GUIX Studio Revision 5.4.2.9                                               */
/*  Date (dd.mm.yyyy): 12. 3.2022   Time (hh:mm): 10:50                        */
/*******************************************************************************/


#ifndef _MUREVA_LCU_DEMO_LCU_MAINDISPLAY_RESOURCES_H_
#define _MUREVA_LCU_DEMO_LCU_MAINDISPLAY_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define LCU_MAINDISPLAY 0
#define LCU_MAINDISPLAY_COLOR_FORMAT GX_COLOR_FORMAT_24XRGB
#define LCU_MAINDISPLAY_X_RESOLUTION 320
#define LCU_MAINDISPLAY_Y_RESOLUTION 540
#define LCU_MAINDISPLAY_THEME_1 0
#define LCU_MAINDISPLAY_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define LCU_MAINDISPLAY_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_CANVAS 0
#define GX_COLOR_ID_WIDGET_FILL 1
#define GX_COLOR_ID_WINDOW_FILL 2
#define GX_COLOR_ID_DEFAULT_BORDER 3
#define GX_COLOR_ID_WINDOW_BORDER 4
#define GX_COLOR_ID_TEXT 5
#define GX_COLOR_ID_SELECTED_TEXT 6
#define GX_COLOR_ID_SELECTED_FILL 7
#define GX_COLOR_ID_SHADOW 8
#define GX_COLOR_ID_SHINE 9
#define GX_COLOR_ID_BTN_BORDER 10
#define GX_COLOR_ID_BTN_UPPER 11
#define GX_COLOR_ID_BTN_LOWER 12
#define GX_COLOR_ID_BTN_TEXT 13
#define GX_COLOR_ID_SCROLL_FILL 14
#define GX_COLOR_ID_SCROLL_BUTTON 15
#define GX_COLOR_ID_TEXT_INPUT_TEXT 16
#define GX_COLOR_ID_TEXT_INPUT_FILL 17
#define GX_COLOR_ID_SLIDER_TICK 18
#define GX_COLOR_ID_SLIDER_GROOVE_TOP 19
#define GX_COLOR_ID_SLIDER_GROOVE_BOTTOM 20
#define GX_COLOR_ID_SLIDER_NEEDLE_OUTLINE 21
#define GX_COLOR_ID_SLIDER_NEEDLE_FILL 22
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE1 23
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE2 24
#define GX_COLOR_ID_DISABLED_TEXT 25
#define GX_COLOR_ID_DISABLED_FILL 26
#define GX_COLOR_ID_READONLY_TEXT 27
#define GX_COLOR_ID_READONLY_FILL 28
#define GX_COLOR_ID_GREEN_BRIGHT 29
#define GX_COLOR_ID_YELLOW 30
#define GX_COLOR_ID_RADIAL_PROGRESS_BAR_FILL 31
#define GX_COLOR_ID_WHITE 32
#define GX_COLOR_ID_RED_BURNT 33
#define GX_COLOR_ID_GREEN_SUBTLE 34
#define GX_COLOR_ID_RED 35
#define LCU_MAINDISPLAY_COLOR_TABLE_SIZE 36

/* Font ID definitions                                                         */

#define GX_FONT_ID_SYSTEM 0
#define GX_FONT_ID_BUTTON 1
#define GX_FONT_ID_PROMPT 2
#define GX_FONT_ID_TEXT_INPUT 3
#define GX_FONT_ID_VERA_24 4
#define GX_FONT_ID_VERA_BI_36 5
#define GX_FONT_ID_VERA_20 6
#define GX_FONT_ID_ARIAL_16 7
#define GX_FONT_ID_ARIAL_20 8
#define GX_FONT_ID_ARIAL_11PT 9
#define GX_FONT_ID_VERABI_12 10
#define GX_FONT_ID_VERABD_48 11
#define GX_FONT_ID_ARIAL_52 12
#define GX_FONT_ID_ARIALBOLD_52 13
#define LCU_MAINDISPLAY_FONT_TABLE_SIZE 14

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_RADIO_ON 1
#define GX_PIXELMAP_ID_RADIO_OFF 2
#define GX_PIXELMAP_ID_CHECKBOX_ON 3
#define GX_PIXELMAP_ID_CHECKBOX_OFF 4
#define GX_PIXELMAP_ID_BACKDROP 5
#define GX_PIXELMAP_ID_BACKDROPA 6
#define GX_PIXELMAP_ID_CLOCK_IMAGE_51_199_40_REV3 7
#define GX_PIXELMAP_ID_DISPLAYRING 8
#define GX_PIXELMAP_ID_DISPLAYRINGA 9
#define GX_PIXELMAP_ID_GREENTICKS 10
#define GX_PIXELMAP_ID_MUREVA_LOGO_133X126 11
#define GX_PIXELMAP_ID_MUREVA_LOGO_180X180 12
#define GX_PIXELMAP_ID_MUREVA_LOGO_REV2 13
#define GX_PIXELMAP_ID_MUREVA_LOGO_ROUNDWHITE 14
#define GX_PIXELMAP_ID_ONESECONDTICKSAMPLE 15
#define GX_PIXELMAP_ID_PAUSEBUTTON_24X16 16
#define GX_PIXELMAP_ID_PAUSEBUTTON_30X20 17
#define GX_PIXELMAP_ID_PAUSEBUTTON_30X30 18
#define GX_PIXELMAP_ID_RED_TEXT_BOX 19
#define GX_PIXELMAP_ID_RIGHTARROW_80X60 20
#define GX_PIXELMAP_ID_SCREENSAVER_TRANSPARENT 21
#define GX_PIXELMAP_ID_STATUSRING_BLUE 22
#define GX_PIXELMAP_ID_STATUSRING_GREEN 23
#define GX_PIXELMAP_ID_STATUSRING_OFF 24
#define GX_PIXELMAP_ID_STATUSRING_RED 25
#define GX_PIXELMAP_ID_STATUSRING_WHITE 26
#define GX_PIXELMAP_ID_WHITE_TEXT_BOX 27
#define LCU_MAINDISPLAY_PIXELMAP_TABLE_SIZE 28

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_25 2
#define GX_STRING_ID_STRING_26 3
#define GX_STRING_ID_STRING_27 4
#define GX_STRING_ID_STRING_28 5
#define GX_STRING_ID_STRING_29 6
#define GX_STRING_ID_STRING_30 7
#define GX_STRING_ID_STRING_2 8
#define GX_STRING_ID_STRING_3 9
#define GX_STRING_ID_STRING_4 10
#define GX_STRING_ID_STRING_5 11
#define GX_STRING_ID_STRING_6 12
#define GX_STRING_ID_STRING_7 13
#define GX_STRING_ID_STRING_10 14
#define GX_STRING_ID_STRING_8 15
#define GX_STRING_ID_STRING_9 16
#define GX_STRING_ID_DETACH 17
#define GX_STRING_ID_STRING_12 18
#define GX_STRING_ID_STRING_13 19
#define GX_STRING_ID_STRING_14 20
#define GX_STRING_ID_STRING_15 21
#define GX_STRING_ID_STRING_16 22
#define GX_STRING_ID_STRING_17 23
#define GX_STRING_ID_STRING_18 24
#define GX_STRING_ID_STRING_19 25
#define GX_STRING_ID_STRING_20 26
#define GX_STRING_ID_STRING_22 27
#define GX_STRING_ID_STRING_23 28
#define GX_STRING_ID_STRING_24 29
#define GX_STRING_ID_STRING_31 30
#define GX_STRING_ID_STRING_32 31
#define GX_STRING_ID_STRING_33 32
#define GX_STRING_ID_STRING_34 33
#define GX_STRING_ID_STRING_39 34
#define GX_STRING_ID_STRING_40 35
#define GX_STRING_ID_STRING_35 36
#define GX_STRING_ID_STRING_36 37
#define GX_STRING_ID_STRING_37 38
#define GX_STRING_ID_VERSION 39
#define GX_STRING_ID_STRING_41 40
#define GX_STRING_ID_STRING_42 41
#define GX_STRING_ID_STRING_43 42
#define GX_STRING_ID_STRING_44 43
#define GX_STRING_ID_STRING_45 44
#define GX_STRING_ID_STRING_46 45
#define GX_STRING_ID_STRING_47 46
#define GX_STRING_ID_STRING_48 47
#define GX_STRING_ID_ATTACH 48
#define GX_STRING_ID_STRING_11 49
#define GX_STRING_ID_STRING_49 50
#define GX_STRING_ID_STRING_21 51
#define GX_STRING_ID_STRING_38 52
#define LCU_MAINDISPLAY_STRING_TABLE_SIZE 53

#endif                                       /* sentry                         */
