/*******************************************************************************/
/*  This file is auto-generated by GUIX Studio. Do not edit this file by hand. */
/*  Modifications to this file should only be made by running the GUIX Studio  */
/*  application and re-generating the application. For more information please */
/*  refer to the GUIX Studio user's guide, or visit our web site at            */
/*  www.expresslogic.com.                                                      */
/*                                                                             */
/*  GUIX Studio Revision 5.4.2.9                                               */
/*  Date (dd.mm.yyyy): 21. 2.2022   Time (hh:mm): 17:30                        */
/*******************************************************************************/


#ifndef _MUREVA_LCU_DEMO_SPECIFICATIONS_H_
#define _MUREVA_LCU_DEMO_SPECIFICATIONS_H_

#include "gx_api.h"

/* Determine if C++ compiler is being used, if so use standard C.              */
#ifdef __cplusplus
extern   "C" {
#endif

/* Define widget ids                                                           */

#define STATUS_RING_ICON 1
#define TIME_PROMPT_ID 2
#define INFORMATION_BUTTON 3
#define GREEN_TICK_ICON 4
#define WHITE_BOX_ICON 5
#define ALTERNATE_TIME_CHECK_BOX 6
#define SPLASH_WINDOW 7
#define EEPROM_FAIL_BTN_ID 8
#define EEPROM_OK_BTN_ID 9
#define EEPROM_EXPIRED_BTN_ID 10
#define PLAY_BTN_ID 11
#define SYSTEM_ERROR_BTN_ID 12
#define MOUTHPIECE_PROMPT_ID 13
#define LIMIT_SWITCH_BTN_ID 14
#define MOUTCHPIECE_IS_LABEL_ID 15
#define SERIAL_NUMBER_PROMPT_ID 16
#define SERIAL_NUMBER_TEXT_INPUT_ID 17


/* Define animation ids                                                        */

#define GX_NEXT_ANIMATION_ID 1


/* Define user event ids                                                       */

#define GX_NEXT_USER_EVENT_ID GX_FIRST_USER_EVENT


/* Declare properties structures for each utilized widget type                 */

typedef struct GX_STUDIO_WIDGET_STRUCT
{
   GX_CHAR *widget_name;
   USHORT  widget_type;
   USHORT  widget_id;
   #if defined(GX_WIDGET_USER_DATA)
   INT   user_data;
   #endif
   ULONG style;
   ULONG status;
   ULONG control_block_size;
   GX_RESOURCE_ID normal_fill_color_id;
   GX_RESOURCE_ID selected_fill_color_id;
   GX_RESOURCE_ID disabled_fill_color_id;
   UINT (*create_function) (GX_CONST struct GX_STUDIO_WIDGET_STRUCT *, GX_WIDGET *, GX_WIDGET *);
   void (*draw_function) (GX_WIDGET *);
   UINT (*event_function) (GX_WIDGET *, GX_EVENT *);
   GX_RECTANGLE size;
   GX_CONST struct GX_STUDIO_WIDGET_STRUCT *next_widget;
   GX_CONST struct GX_STUDIO_WIDGET_STRUCT *child_widget;
   ULONG control_block_offset;
   GX_CONST void *properties;
} GX_STUDIO_WIDGET;

typedef struct
{
    GX_CONST GX_STUDIO_WIDGET *widget_information;
    GX_WIDGET        *widget;
} GX_STUDIO_WIDGET_ENTRY;

typedef struct
{
    GX_RESOURCE_ID string_id; 
    GX_RESOURCE_ID font_id;
    GX_RESOURCE_ID normal_text_color_id;
    GX_RESOURCE_ID selected_text_color_id;
    GX_RESOURCE_ID disabled_text_color_id;
} GX_TEXT_BUTTON_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID string_id; 
    GX_RESOURCE_ID font_id;
    GX_RESOURCE_ID normal_text_color_id;
    GX_RESOURCE_ID selected_text_color_id;
    GX_RESOURCE_ID disabled_text_color_id;
} GX_ML_TEXT_BUTTON_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID string_id; 
    GX_RESOURCE_ID font_id;
    GX_RESOURCE_ID normal_text_color_id;
    GX_RESOURCE_ID selected_text_color_id;
    GX_RESOURCE_ID disabled_text_color_id;
    GX_RESOURCE_ID unchecked_pixelmap_id;
    GX_RESOURCE_ID checked_pixelmap_id;
    GX_RESOURCE_ID unchecked_disabled_pixelmap_id;
    GX_RESOURCE_ID checked_disabled_pixelmap_id;
} GX_CHECKBOX_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID pixelmap_id;
} GX_ICON_BUTTON_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID normal_pixelmap_id;
    GX_RESOURCE_ID selected_pixelmap_id;
} GX_ICON_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID string_id;
    GX_RESOURCE_ID font_id;
    GX_RESOURCE_ID normal_text_color_id;
    GX_RESOURCE_ID selected_text_color_id;
    GX_RESOURCE_ID disabled_text_color_id;
} GX_PROMPT_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID wallpaper_id;
} GX_WINDOW_PROPERTIES;

typedef struct
{
    GX_RESOURCE_ID string_id;
    GX_RESOURCE_ID font_id;
    GX_RESOURCE_ID normal_text_color_id;
    GX_RESOURCE_ID selected_text_color_id;
    GX_RESOURCE_ID disabled_text_color_id;
    GX_RESOURCE_ID readonly_fill_color_id;
    GX_RESOURCE_ID readonly_text_color_id;
    GX_CHAR *buffer;
    UINT buffer_size;
} GX_SINGLE_LINE_TEXT_INPUT_PROPERTIES;

typedef struct
{
   GX_CONST GX_STUDIO_WIDGET *base_info;
   UINT (*base_create_function) (GX_CONST struct GX_STUDIO_WIDGET_STRUCT *, GX_WIDGET *, GX_WIDGET *);
   GX_RECTANGLE size;
} GX_TEMPLATE_PROPERTIES;


/* Declare top-level control blocks                                            */

typedef struct PRIMARYTEMPLATE_CONTROL_BLOCK_STRUCT
{
    GX_WINDOW_MEMBERS_DECLARE
    GX_ICON_BUTTON PrimaryTemplate_LimitSwitchStatus_IconButton;
    GX_PROMPT PrimaryTemplate_EEPROM_Is_Prompt;
    GX_TEXT_BUTTON PrimaryTemplate_EEPROM_Fail_Button;
    GX_TEXT_BUTTON PrimaryTemplate_EEPROM_OK_Button;
    GX_TEXT_BUTTON PrimaryTemplate_EEPROM_Expired_Button;
    GX_ICON_BUTTON PrimaryTemplate_Play_Button;
    GX_MULTI_LINE_TEXT_BUTTON PrimaryTemplate_SystemError_Button;
    GX_PROMPT PrimaryTemplate_Mouthpiece_Prompt;
    GX_TEXT_BUTTON PrimaryTemplate_LimitSwitch_Button;
    GX_PROMPT PrimaryTemplate_LimitSwitchStatus_prompt;
    GX_PROMPT PrimaryTemplate_Mouthpiece_Label;
    GX_PROMPT PrimaryTemplate_SerialNumber_Prompt;
    GX_SINGLE_LINE_TEXT_INPUT PrimaryTemplate_SerialNumber_TextInput;
} PRIMARYTEMPLATE_CONTROL_BLOCK;

typedef struct READYSCREEN_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_ICON ReadyScreen_StatusRing_Icon;
    GX_RADIAL_PROGRESS_BAR ReadyScreen_TherpayTime_RadialProgressBar;
    GX_ICON_BUTTON ReadyScreen_PauseIcon_Button;
    GX_PROMPT ReadyScreen_Time_Prompt;
    GX_MULTI_LINE_TEXT_BUTTON ReadyScreen_Information_Button;
    GX_ICON ReadyScreen_GreenTick_Icon;
    GX_ICON ReadyScreen_WhiteBox_Icon;
    GX_CHECKBOX ReadyScreen_AlternateTime_CheckBox;
} READYSCREEN_CONTROL_BLOCK;

typedef struct SPLASH_WINDOW_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_ICON Splash_Window_MuReva_Logo;
    GX_ICON Splash_Window_StatusRing_Icon;
    GX_PROMPT Splash_Window_Version_Prompt;
    GX_ICON Splash_Window_Mureva_Logo_320x240;
} SPLASH_WINDOW_CONTROL_BLOCK;

typedef struct SAMPLE_TICK_WINDOW_CONTROL_BLOCK_STRUCT
{
    PRIMARYTEMPLATE_CONTROL_BLOCK base;
    GX_ICON Sample_Tick_Window_OneOfSixtyTicks_icon;
} SAMPLE_TICK_WINDOW_CONTROL_BLOCK;


/* extern statically defined control blocks                                    */

#ifndef GUIX_STUDIO_GENERATED_FILE
extern READYSCREEN_CONTROL_BLOCK ReadyScreen;
extern SPLASH_WINDOW_CONTROL_BLOCK Splash_Window;
extern SAMPLE_TICK_WINDOW_CONTROL_BLOCK Sample_Tick_Window;
extern PRIMARYTEMPLATE_CONTROL_BLOCK PrimaryTemplate;
#endif

/* Declare event process functions, draw functions, and callback functions     */

UINT ReadyScreen_Event_Function(GX_WINDOW *widget, GX_EVENT *event_ptr);
VOID ReadyScreen_Draw_Function(GX_WINDOW *widget);
UINT SplashScreen_Event_Function(GX_WINDOW *widget, GX_EVENT *event_ptr);

/* Declare the GX_STUDIO_DISPLAY_INFO structure                                */


typedef struct GX_STUDIO_DISPLAY_INFO_STRUCT 
{
    GX_CONST GX_CHAR *name;
    GX_CONST GX_CHAR *canvas_name;
    GX_CONST GX_THEME **theme_table;
    GX_CONST GX_CHAR ***language_table;
    USHORT   theme_table_size;
    USHORT   language_table_size;
    UINT     string_table_size;
    UINT     x_resolution;
    UINT     y_resolution;
    GX_DISPLAY *display;
    GX_CANVAS  *canvas;
    GX_WINDOW_ROOT *root_window;
    GX_COLOR   *canvas_memory;
    ULONG      canvas_memory_size;
} GX_STUDIO_DISPLAY_INFO;


/* Declare Studio-generated functions for creating top-level widgets           */

UINT gx_studio_text_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_multi_line_text_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_checkbox_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_icon_button_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_icon_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_radial_progress_bar_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_prompt_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_window_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_text_input_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
UINT gx_studio_template_create(GX_CONST GX_STUDIO_WIDGET *info, GX_WIDGET *control_block, GX_WIDGET *parent);
GX_WIDGET *gx_studio_widget_create(GX_BYTE *storage, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent);
UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent, GX_WIDGET **new_widget);
UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *), GX_UBYTE language, USHORT theme, GX_WINDOW_ROOT **return_root);

/* Determine if a C++ compiler is being used.  If so, complete the standard
  C conditional started above.                                                 */
#ifdef __cplusplus
}
#endif

#endif                                       /* sentry                         */
